//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    With additional support for multiple files.
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Infrastructure.Core.DataAccess {
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using Infrastructure.Models;
    using LinqToDB;
    using LinqToDB.Mapping;
    using Type = Models.Type;
    using Version = Models.Version;

    /// <summary>
    /// Database       : pkmn
    /// Data Source    : localhost
    /// Server Version : 5.5.5-10.1.26-MariaDB
    /// </summary>
    public partial class DatabaseContext : LinqToDB.Data.DataConnection {
        /// <summary>
        /// VIEW
        /// </summary>
        public ITable<AbilitiesView> AbilitiesViews { get { return this.GetTable<AbilitiesView>(); } }
        public ITable<Ability> Abilities { get { return this.GetTable<Ability>(); } }
        public ITable<AbilityChangelog> AbilityChangelogs { get { return this.GetTable<AbilityChangelog>(); } }
        public ITable<AbilityChangelogProse> AbilityChangelogProses { get { return this.GetTable<AbilityChangelogProse>(); } }
        public ITable<AbilityFlavorText> AbilityFlavorTexts { get { return this.GetTable<AbilityFlavorText>(); } }
        public ITable<AbilityName> AbilityNames { get { return this.GetTable<AbilityName>(); } }
        public ITable<AbilityProse> AbilityProses { get { return this.GetTable<AbilityProse>(); } }
        public ITable<Berry> Berries { get { return this.GetTable<Berry>(); } }
        public ITable<BerryFirmness> BerryFirmnesses { get { return this.GetTable<BerryFirmness>(); } }
        public ITable<BerryFirmnessName> BerryFirmnessNames { get { return this.GetTable<BerryFirmnessName>(); } }
        public ITable<BerryFlavor> BerryFlavors { get { return this.GetTable<BerryFlavor>(); } }
        public ITable<Characteristic> Characteristics { get { return this.GetTable<Characteristic>(); } }
        public ITable<CharacteristicText> CharacteristicTexts { get { return this.GetTable<CharacteristicText>(); } }
        public ITable<ConquestEpisode> ConquestEpisodes { get { return this.GetTable<ConquestEpisode>(); } }
        public ITable<ConquestEpisodeName> ConquestEpisodeNames { get { return this.GetTable<ConquestEpisodeName>(); } }
        public ITable<ConquestEpisodeWarrior> ConquestEpisodeWarriors { get { return this.GetTable<ConquestEpisodeWarrior>(); } }
        public ITable<ConquestKingdom> ConquestKingdoms { get { return this.GetTable<ConquestKingdom>(); } }
        public ITable<ConquestKingdomName> ConquestKingdomNames { get { return this.GetTable<ConquestKingdomName>(); } }
        public ITable<ConquestMaxLink> ConquestMaxLinks { get { return this.GetTable<ConquestMaxLink>(); } }
        public ITable<ConquestMoveData> ConquestMoveData { get { return this.GetTable<ConquestMoveData>(); } }
        public ITable<ConquestMoveDisplacement> ConquestMoveDisplacements { get { return this.GetTable<ConquestMoveDisplacement>(); } }
        public ITable<ConquestMoveDisplacementProse> ConquestMoveDisplacementProses { get { return this.GetTable<ConquestMoveDisplacementProse>(); } }
        public ITable<ConquestMoveEffect> ConquestMoveEffects { get { return this.GetTable<ConquestMoveEffect>(); } }
        public ITable<ConquestMoveEffectProse> ConquestMoveEffectProses { get { return this.GetTable<ConquestMoveEffectProse>(); } }
        public ITable<ConquestMoveRange> ConquestMoveRanges { get { return this.GetTable<ConquestMoveRange>(); } }
        public ITable<ConquestMoveRangeProse> ConquestMoveRangeProses { get { return this.GetTable<ConquestMoveRangeProse>(); } }
        public ITable<ConquestPokemonAbility> ConquestPokemonAbilities { get { return this.GetTable<ConquestPokemonAbility>(); } }
        public ITable<ConquestPokemonEvolution> ConquestPokemonEvolutions { get { return this.GetTable<ConquestPokemonEvolution>(); } }
        public ITable<ConquestPokemonMove> ConquestPokemonMoves { get { return this.GetTable<ConquestPokemonMove>(); } }
        public ITable<ConquestPokemonStat> ConquestPokemonStats { get { return this.GetTable<ConquestPokemonStat>(); } }
        public ITable<ConquestStat> ConquestStats { get { return this.GetTable<ConquestStat>(); } }
        public ITable<ConquestStatName> ConquestStatNames { get { return this.GetTable<ConquestStatName>(); } }
        public ITable<ConquestTransformationPokemon> ConquestTransformationPokemons { get { return this.GetTable<ConquestTransformationPokemon>(); } }
        public ITable<ConquestTransformationWarrior> ConquestTransformationWarriors { get { return this.GetTable<ConquestTransformationWarrior>(); } }
        public ITable<ConquestWarrior> ConquestWarriors { get { return this.GetTable<ConquestWarrior>(); } }
        public ITable<ConquestWarriorArchetype> ConquestWarriorArchetypes { get { return this.GetTable<ConquestWarriorArchetype>(); } }
        public ITable<ConquestWarriorName> ConquestWarriorNames { get { return this.GetTable<ConquestWarriorName>(); } }
        public ITable<ConquestWarriorRank> ConquestWarriorRanks { get { return this.GetTable<ConquestWarriorRank>(); } }
        public ITable<ConquestWarriorRankStatMap> ConquestWarriorRankStatMaps { get { return this.GetTable<ConquestWarriorRankStatMap>(); } }
        public ITable<ConquestWarriorSkill> ConquestWarriorSkills { get { return this.GetTable<ConquestWarriorSkill>(); } }
        public ITable<ConquestWarriorSkillName> ConquestWarriorSkillNames { get { return this.GetTable<ConquestWarriorSkillName>(); } }
        public ITable<ConquestWarriorSpecialty> ConquestWarriorSpecialties { get { return this.GetTable<ConquestWarriorSpecialty>(); } }
        public ITable<ConquestWarriorStat> ConquestWarriorStats { get { return this.GetTable<ConquestWarriorStat>(); } }
        public ITable<ConquestWarriorStatName> ConquestWarriorStatNames { get { return this.GetTable<ConquestWarriorStatName>(); } }
        public ITable<ConquestWarriorTransformation> ConquestWarriorTransformations { get { return this.GetTable<ConquestWarriorTransformation>(); } }
        public ITable<ContestCombo> ContestCombos { get { return this.GetTable<ContestCombo>(); } }
        public ITable<ContestEffect> ContestEffects { get { return this.GetTable<ContestEffect>(); } }
        public ITable<ContestEffectProse> ContestEffectProses { get { return this.GetTable<ContestEffectProse>(); } }
        public ITable<ContestType> ContestTypes { get { return this.GetTable<ContestType>(); } }
        public ITable<ContestTypeName> ContestTypeNames { get { return this.GetTable<ContestTypeName>(); } }
        public ITable<EggGroup> EggGroups { get { return this.GetTable<EggGroup>(); } }
        public ITable<EggGroupProse> EggGroupProses { get { return this.GetTable<EggGroupProse>(); } }
        public ITable<Encounter> Encounters { get { return this.GetTable<Encounter>(); } }
        public ITable<EncounterCondition> EncounterConditions { get { return this.GetTable<EncounterCondition>(); } }
        public ITable<EncounterConditionProse> EncounterConditionProses { get { return this.GetTable<EncounterConditionProse>(); } }
        public ITable<EncounterConditionValue> EncounterConditionValues { get { return this.GetTable<EncounterConditionValue>(); } }
        public ITable<EncounterConditionValueMap> EncounterConditionValueMaps { get { return this.GetTable<EncounterConditionValueMap>(); } }
        public ITable<EncounterConditionValueProse> EncounterConditionValueProses { get { return this.GetTable<EncounterConditionValueProse>(); } }
        public ITable<EncounterMethod> EncounterMethods { get { return this.GetTable<EncounterMethod>(); } }
        public ITable<EncounterMethodProse> EncounterMethodProses { get { return this.GetTable<EncounterMethodProse>(); } }
        public ITable<EncounterSlot> EncounterSlots { get { return this.GetTable<EncounterSlot>(); } }
        public ITable<EvolutionChain> EvolutionChains { get { return this.GetTable<EvolutionChain>(); } }
        public ITable<EvolutionTrigger> EvolutionTriggers { get { return this.GetTable<EvolutionTrigger>(); } }
        public ITable<EvolutionTriggerProse> EvolutionTriggerProses { get { return this.GetTable<EvolutionTriggerProse>(); } }
        public ITable<Experience> Experiences { get { return this.GetTable<Experience>(); } }
        public ITable<Gender> Genders { get { return this.GetTable<Gender>(); } }
        public ITable<Generation> Generations { get { return this.GetTable<Generation>(); } }
        public ITable<GenerationName> GenerationNames { get { return this.GetTable<GenerationName>(); } }
        public ITable<GrowthRate> GrowthRates { get { return this.GetTable<GrowthRate>(); } }
        public ITable<GrowthRateProse> GrowthRateProses { get { return this.GetTable<GrowthRateProse>(); } }
        public ITable<Item> Items { get { return this.GetTable<Item>(); } }
        public ITable<ItemCategory> ItemCategories { get { return this.GetTable<ItemCategory>(); } }
        public ITable<ItemCategoryProse> ItemCategoryProses { get { return this.GetTable<ItemCategoryProse>(); } }
        public ITable<ItemFlag> ItemFlags { get { return this.GetTable<ItemFlag>(); } }
        public ITable<ItemFlagMap> ItemFlagMaps { get { return this.GetTable<ItemFlagMap>(); } }
        public ITable<ItemFlagProse> ItemFlagProses { get { return this.GetTable<ItemFlagProse>(); } }
        public ITable<ItemFlavorSummary> ItemFlavorSummaries { get { return this.GetTable<ItemFlavorSummary>(); } }
        public ITable<ItemFlavorText> ItemFlavorTexts { get { return this.GetTable<ItemFlavorText>(); } }
        public ITable<ItemFlingEffect> ItemFlingEffects { get { return this.GetTable<ItemFlingEffect>(); } }
        public ITable<ItemFlingEffectProse> ItemFlingEffectProses { get { return this.GetTable<ItemFlingEffectProse>(); } }
        public ITable<ItemGameIndex> ItemGameIndices { get { return this.GetTable<ItemGameIndex>(); } }
        public ITable<ItemName> ItemNames { get { return this.GetTable<ItemName>(); } }
        public ITable<ItemPocket> ItemPockets { get { return this.GetTable<ItemPocket>(); } }
        public ITable<ItemPocketName> ItemPocketNames { get { return this.GetTable<ItemPocketName>(); } }
        public ITable<ItemProse> ItemProses { get { return this.GetTable<ItemProse>(); } }
        public ITable<Language> Languages { get { return this.GetTable<Language>(); } }
        public ITable<LanguageName> LanguageNames { get { return this.GetTable<LanguageName>(); } }
        public ITable<Location> Locations { get { return this.GetTable<Location>(); } }
        public ITable<LocationArea> LocationAreas { get { return this.GetTable<LocationArea>(); } }
        public ITable<LocationAreaEncounterRate> LocationAreaEncounterRates { get { return this.GetTable<LocationAreaEncounterRate>(); } }
        public ITable<LocationAreaProse> LocationAreaProses { get { return this.GetTable<LocationAreaProse>(); } }
        public ITable<LocationGameIndex> LocationGameIndices { get { return this.GetTable<LocationGameIndex>(); } }
        public ITable<LocationName> LocationNames { get { return this.GetTable<LocationName>(); } }
        public ITable<Machine> Machines { get { return this.GetTable<Machine>(); } }
        public ITable<Move> Moves { get { return this.GetTable<Move>(); } }
        public ITable<MoveBattleStyle> MoveBattleStyles { get { return this.GetTable<MoveBattleStyle>(); } }
        public ITable<MoveBattleStyleProse> MoveBattleStyleProses { get { return this.GetTable<MoveBattleStyleProse>(); } }
        public ITable<MoveChangelog> MoveChangelogs { get { return this.GetTable<MoveChangelog>(); } }
        public ITable<MoveDamageClass> MoveDamageClasses { get { return this.GetTable<MoveDamageClass>(); } }
        public ITable<MoveDamageClassProse> MoveDamageClassProses { get { return this.GetTable<MoveDamageClassProse>(); } }
        public ITable<MoveEffect> MoveEffects { get { return this.GetTable<MoveEffect>(); } }
        public ITable<MoveEffectChangelog> MoveEffectChangelogs { get { return this.GetTable<MoveEffectChangelog>(); } }
        public ITable<MoveEffectChangelogProse> MoveEffectChangelogProses { get { return this.GetTable<MoveEffectChangelogProse>(); } }
        public ITable<MoveEffectProse> MoveEffectProses { get { return this.GetTable<MoveEffectProse>(); } }
        public ITable<MoveFlag> MoveFlags { get { return this.GetTable<MoveFlag>(); } }
        public ITable<MoveFlagMap> MoveFlagMaps { get { return this.GetTable<MoveFlagMap>(); } }
        public ITable<MoveFlagProse> MoveFlagProses { get { return this.GetTable<MoveFlagProse>(); } }
        public ITable<MoveFlavorSummary> MoveFlavorSummaries { get { return this.GetTable<MoveFlavorSummary>(); } }
        public ITable<MoveFlavorText> MoveFlavorTexts { get { return this.GetTable<MoveFlavorText>(); } }
        public ITable<MoveMeta> MoveMetas { get { return this.GetTable<MoveMeta>(); } }
        public ITable<MoveMetaAilment> MoveMetaAilments { get { return this.GetTable<MoveMetaAilment>(); } }
        public ITable<MoveMetaAilmentName> MoveMetaAilmentNames { get { return this.GetTable<MoveMetaAilmentName>(); } }
        public ITable<MoveMetaCategory> MoveMetaCategories { get { return this.GetTable<MoveMetaCategory>(); } }
        public ITable<MoveMetaCategoryProse> MoveMetaCategoryProses { get { return this.GetTable<MoveMetaCategoryProse>(); } }
        public ITable<MoveMetaStatChange> MoveMetaStatChanges { get { return this.GetTable<MoveMetaStatChange>(); } }
        public ITable<MoveName> MoveNames { get { return this.GetTable<MoveName>(); } }
        public ITable<MoveTarget> MoveTargets { get { return this.GetTable<MoveTarget>(); } }
        public ITable<MoveTargetProse> MoveTargetProses { get { return this.GetTable<MoveTargetProse>(); } }
        public ITable<Nature> Natures { get { return this.GetTable<Nature>(); } }
        public ITable<NatureBattleStylePreference> NatureBattleStylePreferences { get { return this.GetTable<NatureBattleStylePreference>(); } }
        public ITable<NatureName> NatureNames { get { return this.GetTable<NatureName>(); } }
        public ITable<NaturePokeathlonStat> NaturePokeathlonStats { get { return this.GetTable<NaturePokeathlonStat>(); } }
        public ITable<PalPark> PalParks { get { return this.GetTable<PalPark>(); } }
        public ITable<PalParkArea> PalParkAreas { get { return this.GetTable<PalParkArea>(); } }
        public ITable<PalParkAreaName> PalParkAreaNames { get { return this.GetTable<PalParkAreaName>(); } }
        public ITable<PokeathlonStat> PokeathlonStats { get { return this.GetTable<PokeathlonStat>(); } }
        public ITable<PokeathlonStatName> PokeathlonStatNames { get { return this.GetTable<PokeathlonStatName>(); } }
        public ITable<Pokedex> Pokedexes { get { return this.GetTable<Pokedex>(); } }
        public ITable<PokedexProse> PokedexProses { get { return this.GetTable<PokedexProse>(); } }
        public ITable<PokedexVersionGroup> PokedexVersionGroups { get { return this.GetTable<PokedexVersionGroup>(); } }
        public ITable<Pokemon> Pokemons { get { return this.GetTable<Pokemon>(); } }
        public ITable<PokemonAbility> PokemonAbilities { get { return this.GetTable<PokemonAbility>(); } }
        public ITable<PokemonColor> PokemonColors { get { return this.GetTable<PokemonColor>(); } }
        public ITable<PokemonColorName> PokemonColorNames { get { return this.GetTable<PokemonColorName>(); } }
        public ITable<PokemonDexNumber> PokemonDexNumbers { get { return this.GetTable<PokemonDexNumber>(); } }
        public ITable<PokemonEggGroup> PokemonEggGroups { get { return this.GetTable<PokemonEggGroup>(); } }
        public ITable<PokemonEvolution> PokemonEvolutions { get { return this.GetTable<PokemonEvolution>(); } }
        public ITable<PokemonForm> PokemonForms { get { return this.GetTable<PokemonForm>(); } }
        public ITable<PokemonFormGeneration> PokemonFormGenerations { get { return this.GetTable<PokemonFormGeneration>(); } }
        public ITable<PokemonFormName> PokemonFormNames { get { return this.GetTable<PokemonFormName>(); } }
        public ITable<PokemonFormPokeathlonStat> PokemonFormPokeathlonStats { get { return this.GetTable<PokemonFormPokeathlonStat>(); } }
        public ITable<PokemonGameIndex> PokemonGameIndices { get { return this.GetTable<PokemonGameIndex>(); } }
        public ITable<PokemonHabitat> PokemonHabitats { get { return this.GetTable<PokemonHabitat>(); } }
        public ITable<PokemonHabitatName> PokemonHabitatNames { get { return this.GetTable<PokemonHabitatName>(); } }
        public ITable<PokemonItem> PokemonItems { get { return this.GetTable<PokemonItem>(); } }
        public ITable<PokemonMove> PokemonMoves { get { return this.GetTable<PokemonMove>(); } }
        public ITable<PokemonMoveMethod> PokemonMoveMethods { get { return this.GetTable<PokemonMoveMethod>(); } }
        public ITable<PokemonMoveMethodProse> PokemonMoveMethodProses { get { return this.GetTable<PokemonMoveMethodProse>(); } }
        public ITable<PokemonShape> PokemonShapes { get { return this.GetTable<PokemonShape>(); } }
        public ITable<PokemonShapeProse> PokemonShapeProses { get { return this.GetTable<PokemonShapeProse>(); } }
        public ITable<PokemonSpecies> PokemonSpecies { get { return this.GetTable<PokemonSpecies>(); } }
        public ITable<PokemonSpeciesFlavorSummary> PokemonSpeciesFlavorSummaries { get { return this.GetTable<PokemonSpeciesFlavorSummary>(); } }
        public ITable<PokemonSpeciesFlavorText> PokemonSpeciesFlavorTexts { get { return this.GetTable<PokemonSpeciesFlavorText>(); } }
        public ITable<PokemonSpeciesName> PokemonSpeciesNames { get { return this.GetTable<PokemonSpeciesName>(); } }
        public ITable<PokemonSpeciesProse> PokemonSpeciesProses { get { return this.GetTable<PokemonSpeciesProse>(); } }
        public ITable<PokemonStat> PokemonStats { get { return this.GetTable<PokemonStat>(); } }
        public ITable<PokemonType> PokemonTypes { get { return this.GetTable<PokemonType>(); } }
        public ITable<Region> Regions { get { return this.GetTable<Region>(); } }
        public ITable<RegionName> RegionNames { get { return this.GetTable<RegionName>(); } }
        public ITable<Stat> Stats { get { return this.GetTable<Stat>(); } }
        public ITable<StatName> StatNames { get { return this.GetTable<StatName>(); } }
        public ITable<SuperContestCombo> SuperContestCombos { get { return this.GetTable<SuperContestCombo>(); } }
        public ITable<SuperContestEffect> SuperContestEffects { get { return this.GetTable<SuperContestEffect>(); } }
        public ITable<SuperContestEffectProse> SuperContestEffectProses { get { return this.GetTable<SuperContestEffectProse>(); } }
        public ITable<Type> Types { get { return this.GetTable<Type>(); } }
        public ITable<TypeEfficacy> TypeEfficacies { get { return this.GetTable<TypeEfficacy>(); } }
        public ITable<TypeGameIndex> TypeGameIndices { get { return this.GetTable<TypeGameIndex>(); } }
        public ITable<TypeName> TypeNames { get { return this.GetTable<TypeName>(); } }
        public ITable<Version> Versions { get { return this.GetTable<Version>(); } }
        public ITable<VersionGroup> VersionGroups { get { return this.GetTable<VersionGroup>(); } }
        public ITable<VersionGroupPokemonMoveMethod> VersionGroupPokemonMoveMethods { get { return this.GetTable<VersionGroupPokemonMoveMethod>(); } }
        public ITable<VersionGroupRegion> VersionGroupRegions { get { return this.GetTable<VersionGroupRegion>(); } }
        public ITable<VersionName> VersionNames { get { return this.GetTable<VersionName>(); } }

        public DatabaseContext() {
            InitDataContext();
            InitMappingSchema();
        }

        public DatabaseContext(string configuration)
            : base(configuration) {
            InitDataContext();
            InitMappingSchema();
        }

        partial void InitDataContext();
        partial void InitMappingSchema();
    }
}

#pragma warning restore 1591
