//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    With additional support for multiple files.
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Infrastructure.Models
{
	using System;
	using System.Collections.Generic;
	using System.Linq;

	using Infrastructure.Core.Business.Data;

	using LinqToDB;
	using LinqToDB.Mapping;

	/// <summary>
	/// VIEW
	/// </summary>
	[Table("abilities_view", IsView=true)]
	public partial class AbilitiesView : BusinessData
	{
		[Column("ability_id"),            NotNull    ] public int    AbilityId            { get; set; } // int(11)
		[Column("ability_identifier"),    NotNull    ] public string AbilityIdentifier    { get; set; } // varchar(79)
		[Column("is_main_series"),        NotNull    ] public bool   IsMainSeries         { get; set; } // tinyint(1)
		[Column("ability_names"),            Nullable] public string AbilityNames         { get; set; } // text
		[Column("ability_prose"),            Nullable] public string AbilityProse         { get; set; } // text
		[Column("generation_id"),         NotNull    ] public int    GenerationId         { get; set; } // int(11)
		[Column("generation_identifier"), NotNull    ] public string GenerationIdentifier { get; set; } // varchar(79)
		[Column("region_id"),             NotNull    ] public int    RegionId             { get; set; } // int(11)
		[Column("region_identifier"),     NotNull    ] public string RegionIdentifier     { get; set; } // varchar(79)
	}
}

#pragma warning restore 1591
