//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    With additional support for multiple files.
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Infrastructure.Models
{
	using System;
	using System.Collections.Generic;
	using System.Linq;

	using Infrastructure.Core.Business.Data;

	using LinqToDB;
	using LinqToDB.Mapping;

	[Table("ability_flavor_text")]
	public partial class AbilityFlavorText : BusinessData
	{
		[Column("ability_id"),       PrimaryKey(1), NotNull] public int    AbilityId      { get; set; } // int(11)
		[Column("version_group_id"), PrimaryKey(2), NotNull] public int    VersionGroupId { get; set; } // int(11)
		[Column("language_id"),      PrimaryKey(3), NotNull] public int    LanguageId     { get; set; } // int(11)
		[Column("flavor_text"),                     NotNull] public string FlavorText     { get; set; } // text

		#region Associations

		/// <summary>
		/// ability_flavor_text_ibfk_2
		/// </summary>
		[Association(ThisKey="AbilityId", OtherKey="Id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="ability_flavor_text_ibfk_2", BackReferenceName="Abilityflavortextibfks")]
		public Ability Ability { get; set; }

		/// <summary>
		/// ability_flavor_text_ibfk_3
		/// </summary>
		[Association(ThisKey="LanguageId", OtherKey="Id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="ability_flavor_text_ibfk_3", BackReferenceName="Abilityflavortextibfks")]
		public Language Language { get; set; }

		/// <summary>
		/// ability_flavor_text_ibfk_1
		/// </summary>
		[Association(ThisKey="VersionGroupId", OtherKey="Id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="ability_flavor_text_ibfk_1", BackReferenceName="Abilityflavortextibfks")]
		public VersionGroup VersionGroup { get; set; }

		#endregion
	}
}

#pragma warning restore 1591
