//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    With additional support for multiple files.
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Infrastructure.Models
{
	using System;
	using System.Collections.Generic;
	using System.Linq;

	using Infrastructure.Core.Business.Data;

	using LinqToDB;
	using LinqToDB.Mapping;

	[Table("abilities")]
	public partial class Ability : BusinessData
	{
		[Column("id"),             PrimaryKey, NotNull] public int    Id           { get; set; } // int(11)
		[Column("identifier"),                 NotNull] public string Identifier   { get; set; } // varchar(79)
		[Column("generation_id"),              NotNull] public int    GenerationId { get; set; } // int(11)
		[Column("is_main_series"),             NotNull] public bool   IsMainSeries { get; set; } // tinyint(1)

		#region Associations

		/// <summary>
		/// ability_changelog_ibfk_1_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="AbilityId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<AbilityChangelog> Abilitychangelogibfks { get; set; }

		/// <summary>
		/// ability_flavor_text_ibfk_2_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="AbilityId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<AbilityFlavorText> Abilityflavortextibfks { get; set; }

		/// <summary>
		/// ability_names_ibfk_2_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="AbilityId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<AbilityName> Abilitynamesibfks { get; set; }

		/// <summary>
		/// ability_prose_ibfk_2_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="AbilityId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<AbilityProse> Abilityproseibfks { get; set; }

		/// <summary>
		/// conquest_pokemon_abilities_ibfk_2_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="AbilityId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<ConquestPokemonAbility> Conquestpokemonibfks { get; set; }

		/// <summary>
		/// abilities_ibfk_1
		/// </summary>
		[Association(ThisKey="GenerationId", OtherKey="Id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="abilities_ibfk_1", BackReferenceName="Abilitiesibfks")]
		public Generation Generation { get; set; }

		/// <summary>
		/// pokemon_abilities_ibfk_2_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="AbilityId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<PokemonAbility> Pokemonibfks { get; set; }

		#endregion
	}
}

#pragma warning restore 1591
