//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    With additional support for multiple files.
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Infrastructure.Models
{
	using System;
	using System.Collections.Generic;
	using System.Linq;

	using Infrastructure.Core.Business.Data;

	using LinqToDB;
	using LinqToDB.Mapping;

	[Table("ability_changelog")]
	public partial class AbilityChangelog : BusinessData
	{
		[Column("id"),                          PrimaryKey, NotNull] public int Id                      { get; set; } // int(11)
		[Column("ability_id"),                              NotNull] public int AbilityId               { get; set; } // int(11)
		[Column("changed_in_version_group_id"),             NotNull] public int ChangedInVersionGroupId { get; set; } // int(11)

		#region Associations

		/// <summary>
		/// ability_changelog_ibfk_1
		/// </summary>
		[Association(ThisKey="AbilityId", OtherKey="Id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="ability_changelog_ibfk_1", BackReferenceName="Abilitychangelogibfks")]
		public Ability Ability { get; set; }

		/// <summary>
		/// ability_changelog_prose_ibfk_1_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="AbilityChangelogId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<AbilityChangelogProse> Abilitychangelogproseibfks { get; set; }

		/// <summary>
		/// ability_changelog_ibfk_2
		/// </summary>
		[Association(ThisKey="ChangedInVersionGroupId", OtherKey="Id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="ability_changelog_ibfk_2", BackReferenceName="Abilitychangelogibfks")]
		public VersionGroup ChangedInVersionGroup { get; set; }

		#endregion
	}
}

#pragma warning restore 1591
