//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    With additional support for multiple files.
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Infrastructure.Models
{
	using System;
	using System.Collections.Generic;
	using System.Linq;

	using Infrastructure.Core.Business.Data;

	using LinqToDB;
	using LinqToDB.Mapping;

	[Table("berries")]
	public partial class Berry : BusinessData
	{
		[Column("id"),                   PrimaryKey,  NotNull] public int  Id                { get; set; } // int(11)
		[Column("item_id"),                           NotNull] public int  ItemId            { get; set; } // int(11)
		[Column("firmness_id"),                       NotNull] public int  FirmnessId        { get; set; } // int(11)
		[Column("natural_gift_power"),      Nullable         ] public int? NaturalGiftPower  { get; set; } // int(11)
		[Column("natural_gift_type_id"),    Nullable         ] public int? NaturalGiftTypeId { get; set; } // int(11)
		[Column("size"),                              NotNull] public int  Size              { get; set; } // int(11)
		[Column("max_harvest"),                       NotNull] public int  MaxHarvest        { get; set; } // int(11)
		[Column("growth_time"),                       NotNull] public int  GrowthTime        { get; set; } // int(11)
		[Column("soil_dryness"),                      NotNull] public int  SoilDryness       { get; set; } // int(11)
		[Column("smoothness"),                        NotNull] public int  Smoothness        { get; set; } // int(11)

		#region Associations

		/// <summary>
		/// berry_flavors_ibfk_2_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="BerryId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<BerryFlavor> Berryflavorsibfks { get; set; }

		/// <summary>
		/// berries_ibfk_3
		/// </summary>
		[Association(ThisKey="FirmnessId", OtherKey="Id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="berries_ibfk_3", BackReferenceName="Berriesibfks")]
		public BerryFirmness Firmness { get; set; }

		/// <summary>
		/// berries_ibfk_2
		/// </summary>
		[Association(ThisKey="ItemId", OtherKey="Id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="berries_ibfk_2", BackReferenceName="Berriesibfks")]
		public Item Item { get; set; }

		/// <summary>
		/// berries_ibfk_1
		/// </summary>
		[Association(ThisKey="NaturalGiftTypeId", OtherKey="Id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="berries_ibfk_1", BackReferenceName="Berriesibfks")]
		public Type NaturalGiftType { get; set; }

		#endregion
	}
}

#pragma warning restore 1591
