//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    With additional support for multiple files.
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Infrastructure.Models
{
	using System;
	using System.Collections.Generic;
	using System.Linq;

	using Infrastructure.Core.Business.Data;

	using LinqToDB;
	using LinqToDB.Mapping;

	[Table("berry_flavors")]
	public partial class BerryFlavor : BusinessData
	{
		[Column("berry_id"),        PrimaryKey(1), NotNull] public int BerryId       { get; set; } // int(11)
		[Column("contest_type_id"), PrimaryKey(2), NotNull] public int ContestTypeId { get; set; } // int(11)
		[Column("flavor"),                         NotNull] public int Flavor        { get; set; } // int(11)

		#region Associations

		/// <summary>
		/// berry_flavors_ibfk_2
		/// </summary>
		[Association(ThisKey="BerryId", OtherKey="Id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="berry_flavors_ibfk_2", BackReferenceName="Berryflavorsibfks")]
		public Berry Berry { get; set; }

		/// <summary>
		/// berry_flavors_ibfk_1
		/// </summary>
		[Association(ThisKey="ContestTypeId", OtherKey="Id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="berry_flavors_ibfk_1", BackReferenceName="Berryflavorsibfks")]
		public ContestType ContestType { get; set; }

		#endregion
	}
}

#pragma warning restore 1591
