//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    With additional support for multiple files.
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Infrastructure.Models
{
	using System;
	using System.Collections.Generic;
	using System.Linq;

	using Infrastructure.Core.Business.Data;

	using LinqToDB;
	using LinqToDB.Mapping;

	[Table("characteristics")]
	public partial class Characteristic : BusinessData
	{
		[Column("id"),         PrimaryKey, NotNull] public int Id       { get; set; } // int(11)
		[Column("stat_id"),                NotNull] public int StatId   { get; set; } // int(11)
		[Column("gene_mod_5"),             NotNull] public int GeneMod5 { get; set; } // int(11)

		#region Associations

		/// <summary>
		/// characteristic_text_ibfk_1_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="CharacteristicId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<CharacteristicText> Characteristictextibfks { get; set; }

		/// <summary>
		/// characteristics_ibfk_1
		/// </summary>
		[Association(ThisKey="StatId", OtherKey="Id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="characteristics_ibfk_1", BackReferenceName="Characteristicsibfks")]
		public Stat Stat { get; set; }

		#endregion
	}
}

#pragma warning restore 1591
