//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    With additional support for multiple files.
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Infrastructure.Models
{
	using System;
	using System.Collections.Generic;
	using System.Linq;

	using Infrastructure.Core.Business.Data;

	using LinqToDB;
	using LinqToDB.Mapping;

	[Table("conquest_warrior_ranks")]
	public partial class ConquestWarriorRank : BusinessData
	{
		[Column("id"),         PrimaryKey, NotNull] public int Id        { get; set; } // int(11)
		[Column("warrior_id"),             NotNull] public int WarriorId { get; set; } // int(11)
		[Column("rank"),                   NotNull] public int Rank      { get; set; } // int(11)
		[Column("skill_id"),               NotNull] public int SkillId   { get; set; } // int(11)

		#region Associations

		/// <summary>
		/// conquest_max_links_ibfk_2_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="WarriorRankId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<ConquestMaxLink> Conquestmaxlinksibfks { get; set; }

		/// <summary>
		/// conquest_warrior_rank_stat_map_ibfk_2_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="WarriorRankId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<ConquestWarriorRankStatMap> Conquestwarriorrankstatmapibfks { get; set; }

		/// <summary>
		/// conquest_warrior_transformation_ibfk_4_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="TransformedWarriorRankId", CanBeNull=true, Relationship=Relationship.OneToOne, IsBackReference=true)]
		public ConquestWarriorTransformation Conquestwarriortransformationibfk { get; set; }

		/// <summary>
		/// conquest_warrior_ranks_ibfk_2
		/// </summary>
		[Association(ThisKey="SkillId", OtherKey="Id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="conquest_warrior_ranks_ibfk_2", BackReferenceName="Conquestwarriorranksibfks")]
		public ConquestWarriorSkill Skill { get; set; }

		/// <summary>
		/// conquest_warrior_ranks_ibfk_1
		/// </summary>
		[Association(ThisKey="WarriorId", OtherKey="Id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="conquest_warrior_ranks_ibfk_1", BackReferenceName="Conquestwarriorranksibfks")]
		public ConquestWarrior Warrior { get; set; }

		#endregion
	}
}

#pragma warning restore 1591
