//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    With additional support for multiple files.
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Infrastructure.Models
{
	using System;
	using System.Collections.Generic;
	using System.Linq;

	using Infrastructure.Core.Business.Data;

	using LinqToDB;
	using LinqToDB.Mapping;

	[Table("conquest_pokemon_stats")]
	public partial class ConquestPokemonStat : BusinessData
	{
		[Column("pokemon_species_id"), PrimaryKey(1), NotNull] public int PokemonSpeciesId { get; set; } // int(11)
		[Column("conquest_stat_id"),   PrimaryKey(2), NotNull] public int ConquestStatId   { get; set; } // int(11)
		[Column("base_stat"),                         NotNull] public int BaseStat         { get; set; } // int(11)

		#region Associations

		/// <summary>
		/// conquest_pokemon_stats_ibfk_1
		/// </summary>
		[Association(ThisKey="ConquestStatId", OtherKey="Id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="conquest_pokemon_stats_ibfk_1", BackReferenceName="Conquestpokemonstatsibfks")]
		public ConquestStat ConquestStat { get; set; }

		/// <summary>
		/// conquest_pokemon_stats_ibfk_2
		/// </summary>
		[Association(ThisKey="PokemonSpeciesId", OtherKey="Id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="conquest_pokemon_stats_ibfk_2", BackReferenceName="Conquestpokemonstatsibfks")]
		public PokemonSpecies PokemonSpecies { get; set; }

		#endregion
	}
}

#pragma warning restore 1591
