//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    With additional support for multiple files.
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Infrastructure.Models
{
	using System;
	using System.Collections.Generic;
	using System.Linq;

	using Infrastructure.Core.Business.Data;

	using LinqToDB;
	using LinqToDB.Mapping;

	[Table("conquest_kingdoms")]
	public partial class ConquestKingdom : BusinessData
	{
		[Column("id"),         PrimaryKey, NotNull] public int    Id         { get; set; } // int(11)
		[Column("identifier"),             NotNull] public string Identifier { get; set; } // varchar(79)
		[Column("type_id"),                NotNull] public int    TypeId     { get; set; } // int(11)

		#region Associations

		/// <summary>
		/// conquest_kingdom_names_ibfk_2_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="KingdomId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<ConquestKingdomName> Conquestkingdomnamesibfks { get; set; }

		/// <summary>
		/// conquest_pokemon_evolution_ibfk_5_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="KingdomId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<ConquestPokemonEvolution> Conquestpokemonevolutionibfks { get; set; }

		/// <summary>
		/// conquest_kingdoms_ibfk_1
		/// </summary>
		[Association(ThisKey="TypeId", OtherKey="Id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="conquest_kingdoms_ibfk_1", BackReferenceName="Conquestkingdomsibfks")]
		public Type Type { get; set; }

		#endregion
	}
}

#pragma warning restore 1591
