//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    With additional support for multiple files.
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Infrastructure.Models
{
	using System;
	using System.Collections.Generic;
	using System.Linq;

	using Infrastructure.Core.Business.Data;

	using LinqToDB;
	using LinqToDB.Mapping;

	[Table("conquest_warrior_transformation")]
	public partial class ConquestWarriorTransformation : BusinessData
	{
		[Column("transformed_warrior_rank_id"), PrimaryKey,  NotNull] public int  TransformedWarriorRankId { get; set; } // int(11)
		[Column("is_automatic"),                             NotNull] public bool IsAutomatic              { get; set; } // tinyint(1)
		[Column("required_link"),                  Nullable         ] public int? RequiredLink             { get; set; } // int(11)
		[Column("completed_episode_id"),           Nullable         ] public int? CompletedEpisodeId       { get; set; } // int(11)
		[Column("current_episode_id"),             Nullable         ] public int? CurrentEpisodeId         { get; set; } // int(11)
		[Column("distant_warrior_id"),             Nullable         ] public int? DistantWarriorId         { get; set; } // int(11)
		[Column("female_warlord_count"),           Nullable         ] public int? FemaleWarlordCount       { get; set; } // int(11)
		[Column("pokemon_count"),                  Nullable         ] public int? PokemonCount             { get; set; } // int(11)
		[Column("collection_type_id"),             Nullable         ] public int? CollectionTypeId         { get; set; } // int(11)
		[Column("warrior_count"),                  Nullable         ] public int? WarriorCount             { get; set; } // int(11)

		#region Associations

		/// <summary>
		/// conquest_warrior_transformation_ibfk_2
		/// </summary>
		[Association(ThisKey="CollectionTypeId", OtherKey="Id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="conquest_warrior_transformation_ibfk_2", BackReferenceName="Conquestwarriortransformationibfks")]
		public Type CollectionType { get; set; }

		/// <summary>
		/// conquest_warrior_transformation_ibfk_1
		/// </summary>
		[Association(ThisKey="CompletedEpisodeId", OtherKey="Id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="conquest_warrior_transformation_ibfk_1", BackReferenceName="Conquestwarriortransformationibfks")]
		public ConquestEpisode CompletedEpisode { get; set; }

		/// <summary>
		/// conquest_transformation_pokemon_ibfk_2_BackReference
		/// </summary>
		[Association(ThisKey="TransformedWarriorRankId", OtherKey="TransformationId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<ConquestTransformationPokemon> Conquesttransformationpokemonibfks { get; set; }

		/// <summary>
		/// conquest_transformation_warriors_ibfk_1_BackReference
		/// </summary>
		[Association(ThisKey="TransformedWarriorRankId", OtherKey="TransformationId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<ConquestTransformationWarrior> Conquesttransformationwarriorsibfks { get; set; }

		/// <summary>
		/// conquest_warrior_transformation_ibfk_3
		/// </summary>
		[Association(ThisKey="CurrentEpisodeId", OtherKey="Id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="conquest_warrior_transformation_ibfk_3", BackReferenceName="ConquestWarriorTransformationIbfk3BackReferences")]
		public ConquestEpisode CurrentEpisode { get; set; }

		/// <summary>
		/// conquest_warrior_transformation_ibfk_5
		/// </summary>
		[Association(ThisKey="DistantWarriorId", OtherKey="Id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="conquest_warrior_transformation_ibfk_5", BackReferenceName="Conquestwarriortransformationibfks")]
		public ConquestWarrior DistantWarrior { get; set; }

		/// <summary>
		/// conquest_warrior_transformation_ibfk_4
		/// </summary>
		[Association(ThisKey="TransformedWarriorRankId", OtherKey="Id", CanBeNull=false, Relationship=Relationship.OneToOne, KeyName="conquest_warrior_transformation_ibfk_4", BackReferenceName="Conquestwarriortransformationibfk")]
		public ConquestWarriorRank TransformedWarriorRank { get; set; }

		#endregion
	}
}

#pragma warning restore 1591
