//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    With additional support for multiple files.
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Infrastructure.Models
{
	using System;
	using System.Collections.Generic;
	using System.Linq;

	using Infrastructure.Core.Business.Data;

	using LinqToDB;
	using LinqToDB.Mapping;

	[Table("conquest_stats")]
	public partial class ConquestStat : BusinessData
	{
		[Column("id"),         PrimaryKey, NotNull] public int    Id         { get; set; } // int(11)
		[Column("identifier"),             NotNull] public string Identifier { get; set; } // varchar(79)
		[Column("is_base"),                NotNull] public bool   IsBase     { get; set; } // tinyint(1)

		#region Associations

		/// <summary>
		/// conquest_pokemon_evolution_ibfk_1_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="RequiredStatId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<ConquestPokemonEvolution> Conquestpokemonevolutionibfks { get; set; }

		/// <summary>
		/// conquest_pokemon_stats_ibfk_1_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="ConquestStatId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<ConquestPokemonStat> Conquestpokemonstatsibfks { get; set; }

		/// <summary>
		/// conquest_stat_names_ibfk_2_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="ConquestStatId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<ConquestStatName> Conqueststatnamesibfks { get; set; }

		#endregion
	}
}

#pragma warning restore 1591
