//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    With additional support for multiple files.
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Infrastructure.Models
{
	using System;
	using System.Collections.Generic;
	using System.Linq;

	using Infrastructure.Core.Business.Data;

	using LinqToDB;
	using LinqToDB.Mapping;

	[Table("conquest_warriors")]
	public partial class ConquestWarrior : BusinessData
	{
		[Column("id"),           PrimaryKey,  NotNull] public int    Id          { get; set; } // int(11)
		[Column("identifier"),                NotNull] public string Identifier  { get; set; } // varchar(79)
		[Column("gender_id"),                 NotNull] public int    GenderId    { get; set; } // int(11)
		[Column("archetype_id"),    Nullable         ] public int?   ArchetypeId { get; set; } // int(11)

		#region Associations

		/// <summary>
		/// conquest_warriors_ibfk_1
		/// </summary>
		[Association(ThisKey="ArchetypeId", OtherKey="Id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="conquest_warriors_ibfk_1", BackReferenceName="Conquestwarriorsibfks")]
		public ConquestWarriorArchetype Archetype { get; set; }

		/// <summary>
		/// conquest_episode_warriors_ibfk_2_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="WarriorId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<ConquestEpisodeWarrior> Conquestepisodewarriorsibfks { get; set; }

		/// <summary>
		/// conquest_transformation_warriors_ibfk_2_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="PresentWarriorId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<ConquestTransformationWarrior> Conquesttransformationwarriorsibfks { get; set; }

		/// <summary>
		/// conquest_warrior_names_ibfk_2_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="WarriorId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<ConquestWarriorName> Conquestwarriornamesibfks { get; set; }

		/// <summary>
		/// conquest_warrior_ranks_ibfk_1_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="WarriorId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<ConquestWarriorRank> Conquestwarriorranksibfks { get; set; }

		/// <summary>
		/// conquest_warrior_specialties_ibfk_1_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="WarriorId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<ConquestWarriorSpecialty> Conquestwarriorspecialtiesibfks { get; set; }

		/// <summary>
		/// conquest_warrior_transformation_ibfk_5_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="DistantWarriorId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<ConquestWarriorTransformation> Conquestwarriortransformationibfks { get; set; }

		/// <summary>
		/// conquest_warriors_ibfk_2
		/// </summary>
		[Association(ThisKey="GenderId", OtherKey="Id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="conquest_warriors_ibfk_2", BackReferenceName="Conquestwarriorsibfks")]
		public Gender Gender { get; set; }

		#endregion
	}
}

#pragma warning restore 1591
