//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    With additional support for multiple files.
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Infrastructure.Models
{
	using System;
	using System.Collections.Generic;
	using System.Linq;

	using Infrastructure.Core.Business.Data;

	using LinqToDB;
	using LinqToDB.Mapping;

	[Table("conquest_pokemon_evolution")]
	public partial class ConquestPokemonEvolution : BusinessData
	{
		[Column("evolved_species_id"),     PrimaryKey,  NotNull] public int  EvolvedSpeciesId     { get; set; } // int(11)
		[Column("required_stat_id"),          Nullable         ] public int? RequiredStatId       { get; set; } // int(11)
		[Column("minimum_stat"),              Nullable         ] public int? MinimumStat          { get; set; } // int(11)
		[Column("minimum_link"),              Nullable         ] public int? MinimumLink          { get; set; } // int(11)
		[Column("kingdom_id"),                Nullable         ] public int? KingdomId            { get; set; } // int(11)
		[Column("warrior_gender_id"),         Nullable         ] public int? WarriorGenderId      { get; set; } // int(11)
		[Column("item_id"),                   Nullable         ] public int? ItemId               { get; set; } // int(11)
		[Column("recruiting_ko_required"),              NotNull] public bool RecruitingKoRequired { get; set; } // tinyint(1)

		#region Associations

		/// <summary>
		/// conquest_pokemon_evolution_ibfk_4
		/// </summary>
		[Association(ThisKey="EvolvedSpeciesId", OtherKey="Id", CanBeNull=false, Relationship=Relationship.OneToOne, KeyName="conquest_pokemon_evolution_ibfk_4", BackReferenceName="Conquestpokemonevolutionibfk")]
		public PokemonSpecies EvolvedSpecies { get; set; }

		/// <summary>
		/// conquest_pokemon_evolution_ibfk_2
		/// </summary>
		[Association(ThisKey="ItemId", OtherKey="Id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="conquest_pokemon_evolution_ibfk_2", BackReferenceName="Conquestpokemonevolutionibfks")]
		public Item Item { get; set; }

		/// <summary>
		/// conquest_pokemon_evolution_ibfk_5
		/// </summary>
		[Association(ThisKey="KingdomId", OtherKey="Id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="conquest_pokemon_evolution_ibfk_5", BackReferenceName="Conquestpokemonevolutionibfks")]
		public ConquestKingdom Kingdom { get; set; }

		/// <summary>
		/// conquest_pokemon_evolution_ibfk_1
		/// </summary>
		[Association(ThisKey="RequiredStatId", OtherKey="Id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="conquest_pokemon_evolution_ibfk_1", BackReferenceName="Conquestpokemonevolutionibfks")]
		public ConquestStat RequiredStat { get; set; }

		/// <summary>
		/// conquest_pokemon_evolution_ibfk_3
		/// </summary>
		[Association(ThisKey="WarriorGenderId", OtherKey="Id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="conquest_pokemon_evolution_ibfk_3", BackReferenceName="Conquestpokemonevolutionibfks")]
		public Gender WarriorGender { get; set; }

		#endregion
	}
}

#pragma warning restore 1591
