//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    With additional support for multiple files.
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Infrastructure.Models
{
	using System;
	using System.Collections.Generic;
	using System.Linq;

	using Infrastructure.Core.Business.Data;

	using LinqToDB;
	using LinqToDB.Mapping;

	[Table("conquest_max_links")]
	public partial class ConquestMaxLink : BusinessData
	{
		[Column("warrior_rank_id"),    PrimaryKey(1), NotNull] public int WarriorRankId    { get; set; } // int(11)
		[Column("pokemon_species_id"), PrimaryKey(2), NotNull] public int PokemonSpeciesId { get; set; } // int(11)
		[Column("max_link"),                          NotNull] public int MaxLink          { get; set; } // int(11)

		#region Associations

		/// <summary>
		/// conquest_max_links_ibfk_1
		/// </summary>
		[Association(ThisKey="PokemonSpeciesId", OtherKey="Id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="conquest_max_links_ibfk_1", BackReferenceName="Conquestmaxlinksibfks")]
		public PokemonSpecies PokemonSpecies { get; set; }

		/// <summary>
		/// conquest_max_links_ibfk_2
		/// </summary>
		[Association(ThisKey="WarriorRankId", OtherKey="Id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="conquest_max_links_ibfk_2", BackReferenceName="Conquestmaxlinksibfks")]
		public ConquestWarriorRank WarriorRank { get; set; }

		#endregion
	}
}

#pragma warning restore 1591
