//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    With additional support for multiple files.
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Infrastructure.Models
{
	using System;
	using System.Collections.Generic;
	using System.Linq;

	using Infrastructure.Core.Business.Data;

	using LinqToDB;
	using LinqToDB.Mapping;

	[Table("conquest_transformation_warriors")]
	public partial class ConquestTransformationWarrior : BusinessData
	{
		[Column("transformation_id"),  PrimaryKey(1), NotNull] public int TransformationId { get; set; } // int(11)
		[Column("present_warrior_id"), PrimaryKey(2), NotNull] public int PresentWarriorId { get; set; } // int(11)

		#region Associations

		/// <summary>
		/// conquest_transformation_warriors_ibfk_2
		/// </summary>
		[Association(ThisKey="PresentWarriorId", OtherKey="Id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="conquest_transformation_warriors_ibfk_2", BackReferenceName="Conquesttransformationwarriorsibfks")]
		public ConquestWarrior PresentWarrior { get; set; }

		/// <summary>
		/// conquest_transformation_warriors_ibfk_1
		/// </summary>
		[Association(ThisKey="TransformationId", OtherKey="TransformedWarriorRankId", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="conquest_transformation_warriors_ibfk_1", BackReferenceName="Conquesttransformationwarriorsibfks")]
		public ConquestWarriorTransformation Transformation { get; set; }

		#endregion
	}
}

#pragma warning restore 1591
