//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    With additional support for multiple files.
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Infrastructure.Models
{
	using System;
	using System.Collections.Generic;
	using System.Linq;

	using Infrastructure.Core.Business.Data;

	using LinqToDB;
	using LinqToDB.Mapping;

	[Table("contest_effects")]
	public partial class ContestEffect : BusinessData
	{
		[Column("id"),     PrimaryKey, NotNull] public int   Id     { get; set; } // int(11)
		[Column("appeal"),             NotNull] public short Appeal { get; set; } // smallint(6)
		[Column("jam"),                NotNull] public short Jam    { get; set; } // smallint(6)

		#region Associations

		/// <summary>
		/// contest_effect_prose_ibfk_1_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="ContestEffectId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<ContestEffectProse> Contesteffectproseibfks { get; set; }

		/// <summary>
		/// moves_ibfk_3_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="ContestEffectId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<Move> Movesibfks { get; set; }

		#endregion
	}
}

#pragma warning restore 1591
