//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    With additional support for multiple files.
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Infrastructure.Models
{
	using System;
	using System.Collections.Generic;
	using System.Linq;

	using Infrastructure.Core.Business.Data;

	using LinqToDB;
	using LinqToDB.Mapping;

	[Table("contest_types")]
	public partial class ContestType : BusinessData
	{
		[Column("id"),         PrimaryKey, NotNull] public int    Id         { get; set; } // int(11)
		[Column("identifier"),             NotNull] public string Identifier { get; set; } // varchar(79)

		#region Associations

		/// <summary>
		/// berry_flavors_ibfk_1_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="ContestTypeId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<BerryFlavor> Berryflavorsibfks { get; set; }

		/// <summary>
		/// contest_type_names_ibfk_1_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="ContestTypeId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<ContestTypeName> Contesttypenamesibfks { get; set; }

		/// <summary>
		/// moves_ibfk_1_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="ContestTypeId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<Move> Movesibfks { get; set; }

		/// <summary>
		/// natures_ibfk_2_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="HatesFlavorId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<Nature> NaturesIbfk2BackReferences { get; set; }

		/// <summary>
		/// natures_ibfk_1_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="LikesFlavorId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<Nature> Naturesibfks { get; set; }

		#endregion
	}
}

#pragma warning restore 1591
