//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    With additional support for multiple files.
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Infrastructure.Models
{
	using System;
	using System.Collections.Generic;
	using System.Linq;

	using Infrastructure.Core.Business.Data;

	using LinqToDB;
	using LinqToDB.Mapping;

	[Table("encounter_slots")]
	public partial class EncounterSlot : BusinessData
	{
		[Column("id"),                  PrimaryKey,  NotNull] public int  Id                { get; set; } // int(11)
		[Column("version_group_id"),                 NotNull] public int  VersionGroupId    { get; set; } // int(11)
		[Column("encounter_method_id"),              NotNull] public int  EncounterMethodId { get; set; } // int(11)
		[Column("slot"),                   Nullable         ] public int? Slot              { get; set; } // int(11)
		[Column("rarity"),                 Nullable         ] public int? Rarity            { get; set; } // int(11)

		#region Associations

		/// <summary>
		/// encounter_slots_ibfk_2
		/// </summary>
		[Association(ThisKey="EncounterMethodId", OtherKey="Id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="encounter_slots_ibfk_2", BackReferenceName="Encounterslotsibfks")]
		public EncounterMethod EncounterMethod { get; set; }

		/// <summary>
		/// encounters_ibfk_2_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="EncounterSlotId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<Encounter> Encountersibfks { get; set; }

		/// <summary>
		/// encounter_slots_ibfk_1
		/// </summary>
		[Association(ThisKey="VersionGroupId", OtherKey="Id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="encounter_slots_ibfk_1", BackReferenceName="Encounterslotsibfks")]
		public VersionGroup VersionGroup { get; set; }

		#endregion
	}
}

#pragma warning restore 1591
