//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    With additional support for multiple files.
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Infrastructure.Models
{
	using System;
	using System.Collections.Generic;
	using System.Linq;

	using Infrastructure.Core.Business.Data;

	using LinqToDB;
	using LinqToDB.Mapping;

	[Table("encounters")]
	public partial class Encounter : BusinessData
	{
		[Column("id"),                PrimaryKey, NotNull] public int Id              { get; set; } // int(11)
		[Column("version_id"),                    NotNull] public int VersionId       { get; set; } // int(11)
		[Column("location_area_id"),              NotNull] public int LocationAreaId  { get; set; } // int(11)
		[Column("encounter_slot_id"),             NotNull] public int EncounterSlotId { get; set; } // int(11)
		[Column("pokemon_id"),                    NotNull] public int PokemonId       { get; set; } // int(11)
		[Column("min_level"),                     NotNull] public int MinLevel        { get; set; } // int(11)
		[Column("max_level"),                     NotNull] public int MaxLevel        { get; set; } // int(11)

		#region Associations

		/// <summary>
		/// encounter_condition_value_map_ibfk_1_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="EncounterId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<EncounterConditionValueMap> Encounterconditionvaluemapibfks { get; set; }

		/// <summary>
		/// encounters_ibfk_2
		/// </summary>
		[Association(ThisKey="EncounterSlotId", OtherKey="Id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="encounters_ibfk_2", BackReferenceName="Encountersibfks")]
		public EncounterSlot EncounterSlot { get; set; }

		/// <summary>
		/// encounters_ibfk_1
		/// </summary>
		[Association(ThisKey="LocationAreaId", OtherKey="Id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="encounters_ibfk_1", BackReferenceName="Encountersibfks")]
		public LocationArea LocationArea { get; set; }

		/// <summary>
		/// encounters_ibfk_4
		/// </summary>
		[Association(ThisKey="PokemonId", OtherKey="Id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="encounters_ibfk_4", BackReferenceName="Encountersibfks")]
		public Pokemon Pokemon { get; set; }

		/// <summary>
		/// encounters_ibfk_3
		/// </summary>
		[Association(ThisKey="VersionId", OtherKey="Id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="encounters_ibfk_3", BackReferenceName="Encountersibfks")]
		public Version Version { get; set; }

		#endregion
	}
}

#pragma warning restore 1591
