//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    With additional support for multiple files.
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Infrastructure.Models
{
	using System;
	using System.Collections.Generic;
	using System.Linq;

	using Infrastructure.Core.Business.Data;

	using LinqToDB;
	using LinqToDB.Mapping;

	[Table("encounter_condition_value_map")]
	public partial class EncounterConditionValueMap : BusinessData
	{
		[Column("encounter_id"),                 PrimaryKey(1), NotNull] public int EncounterId               { get; set; } // int(11)
		[Column("encounter_condition_value_id"), PrimaryKey(2), NotNull] public int EncounterConditionValueId { get; set; } // int(11)

		#region Associations

		/// <summary>
		/// encounter_condition_value_map_ibfk_1
		/// </summary>
		[Association(ThisKey="EncounterId", OtherKey="Id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="encounter_condition_value_map_ibfk_1", BackReferenceName="Encounterconditionvaluemapibfks")]
		public Encounter Encounter { get; set; }

		/// <summary>
		/// encounter_condition_value_map_ibfk_2
		/// </summary>
		[Association(ThisKey="EncounterConditionValueId", OtherKey="Id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="encounter_condition_value_map_ibfk_2", BackReferenceName="Encounterconditionvaluemapibfks")]
		public EncounterConditionValue EncounterConditionValue { get; set; }

		#endregion
	}
}

#pragma warning restore 1591
