//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    With additional support for multiple files.
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Infrastructure.Models
{
	using System;
	using System.Collections.Generic;
	using System.Linq;

	using Infrastructure.Core.Business.Data;

	using LinqToDB;
	using LinqToDB.Mapping;

	[Table("encounter_condition_values")]
	public partial class EncounterConditionValue : BusinessData
	{
		[Column("id"),                     PrimaryKey, NotNull] public int    Id                   { get; set; } // int(11)
		[Column("encounter_condition_id"),             NotNull] public int    EncounterConditionId { get; set; } // int(11)
		[Column("identifier"),                         NotNull] public string Identifier           { get; set; } // varchar(79)
		[Column("is_default"),                         NotNull] public bool   IsDefault            { get; set; } // tinyint(1)

		#region Associations

		/// <summary>
		/// encounter_condition_values_ibfk_1
		/// </summary>
		[Association(ThisKey="EncounterConditionId", OtherKey="Id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="encounter_condition_values_ibfk_1", BackReferenceName="Encounterconditionvaluesibfks")]
		public EncounterCondition EncounterCondition { get; set; }

		/// <summary>
		/// encounter_condition_value_map_ibfk_2_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="EncounterConditionValueId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<EncounterConditionValueMap> Encounterconditionvaluemapibfks { get; set; }

		/// <summary>
		/// encounter_condition_value_prose_ibfk_1_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="EncounterConditionValueId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<EncounterConditionValueProse> Encounterconditionvalueproseibfks { get; set; }

		#endregion
	}
}

#pragma warning restore 1591
