//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    With additional support for multiple files.
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Infrastructure.Models
{
	using System;
	using System.Collections.Generic;
	using System.Linq;

	using Infrastructure.Core.Business.Data;

	using LinqToDB;
	using LinqToDB.Mapping;

	[Table("evolution_chains")]
	public partial class EvolutionChain : BusinessData
	{
		[Column("id"),                   PrimaryKey,  NotNull] public int  Id                { get; set; } // int(11)
		[Column("baby_trigger_item_id"),    Nullable         ] public int? BabyTriggerItemId { get; set; } // int(11)

		#region Associations

		/// <summary>
		/// evolution_chains_ibfk_1
		/// </summary>
		[Association(ThisKey="BabyTriggerItemId", OtherKey="Id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="evolution_chains_ibfk_1", BackReferenceName="Evolutionchainsibfks")]
		public Item BabyTriggerItem { get; set; }

		/// <summary>
		/// pokemon_species_ibfk_1_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="EvolutionChainId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<PokemonSpecies> Pokemonspeciesibfks { get; set; }

		#endregion
	}
}

#pragma warning restore 1591
