//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    With additional support for multiple files.
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Infrastructure.Models
{
	using System;
	using System.Collections.Generic;
	using System.Linq;

	using Infrastructure.Core.Business.Data;

	using LinqToDB;
	using LinqToDB.Mapping;

	[Table("experience")]
	public partial class Experience : BusinessData
	{
		[Column("growth_rate_id"), PrimaryKey(1), NotNull] public int GrowthRateId     { get; set; } // int(11)
		[Column("level"),          PrimaryKey(2), NotNull] public int Level            { get; set; } // int(11)
		[Column("experience"),                    NotNull] public int ExperienceColumn { get; set; } // int(11)

		#region Associations

		/// <summary>
		/// experience_ibfk_1
		/// </summary>
		[Association(ThisKey="GrowthRateId", OtherKey="Id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="experience_ibfk_1", BackReferenceName="Experienceibfks")]
		public GrowthRate GrowthRate { get; set; }

		#endregion
	}
}

#pragma warning restore 1591
