//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    With additional support for multiple files.
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Infrastructure.Models
{
	using System;
	using System.Collections.Generic;
	using System.Linq;

	using Infrastructure.Core.Business.Data;

	using LinqToDB;
	using LinqToDB.Mapping;

	[Table("genders")]
	public partial class Gender : BusinessData
	{
		[Column("id"),         PrimaryKey, NotNull] public int    Id         { get; set; } // int(11)
		[Column("identifier"),             NotNull] public string Identifier { get; set; } // varchar(79)

		#region Associations

		/// <summary>
		/// conquest_pokemon_evolution_ibfk_3_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="WarriorGenderId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<ConquestPokemonEvolution> Conquestpokemonevolutionibfks { get; set; }

		/// <summary>
		/// conquest_warriors_ibfk_2_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="GenderId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<ConquestWarrior> Conquestwarriorsibfks { get; set; }

		/// <summary>
		/// pokemon_evolution_ibfk_5_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="GenderId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<PokemonEvolution> Pokemonevolutionibfks { get; set; }

		#endregion
	}
}

#pragma warning restore 1591
