//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    With additional support for multiple files.
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Infrastructure.Models
{
	using System;
	using System.Collections.Generic;
	using System.Linq;

	using Infrastructure.Core.Business.Data;

	using LinqToDB;
	using LinqToDB.Mapping;

	[Table("growth_rates")]
	public partial class GrowthRate : BusinessData
	{
		[Column("id"),         PrimaryKey, NotNull] public int    Id         { get; set; } // int(11)
		[Column("identifier"),             NotNull] public string Identifier { get; set; } // varchar(79)
		[Column("formula"),                NotNull] public string Formula    { get; set; } // text

		#region Associations

		/// <summary>
		/// experience_ibfk_1_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="GrowthRateId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<Experience> Experienceibfks { get; set; }

		/// <summary>
		/// growth_rate_prose_ibfk_1_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="GrowthRateId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<GrowthRateProse> Growthrateproseibfks { get; set; }

		/// <summary>
		/// pokemon_species_ibfk_7_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="GrowthRateId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<PokemonSpecies> Pokemonspeciesibfks { get; set; }

		#endregion
	}
}

#pragma warning restore 1591
