//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    With additional support for multiple files.
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Infrastructure.Models
{
	using System;
	using System.Collections.Generic;
	using System.Linq;

	using Infrastructure.Core.Business.Data;

	using LinqToDB;
	using LinqToDB.Mapping;

	[Table("items")]
	public partial class Item : BusinessData
	{
		[Column("id"),              PrimaryKey,  NotNull] public int    Id            { get; set; } // int(11)
		[Column("identifier"),                   NotNull] public string Identifier    { get; set; } // varchar(79)
		[Column("category_id"),                  NotNull] public int    CategoryId    { get; set; } // int(11)
		[Column("cost"),                         NotNull] public int    Cost          { get; set; } // int(11)
		[Column("fling_power"),        Nullable         ] public int?   FlingPower    { get; set; } // int(11)
		[Column("fling_effect_id"),    Nullable         ] public int?   FlingEffectId { get; set; } // int(11)

		#region Associations

		/// <summary>
		/// berries_ibfk_2_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="ItemId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<Berry> Berriesibfks { get; set; }

		/// <summary>
		/// items_ibfk_1
		/// </summary>
		[Association(ThisKey="CategoryId", OtherKey="Id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="items_ibfk_1", BackReferenceName="Itemsibfks")]
		public ItemCategory Category { get; set; }

		/// <summary>
		/// conquest_pokemon_evolution_ibfk_2_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="ItemId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<ConquestPokemonEvolution> Conquestpokemonevolutionibfks { get; set; }

		/// <summary>
		/// evolution_chains_ibfk_1_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="BabyTriggerItemId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<EvolutionChain> Evolutionchainsibfks { get; set; }

		/// <summary>
		/// items_ibfk_2
		/// </summary>
		[Association(ThisKey="FlingEffectId", OtherKey="Id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="items_ibfk_2", BackReferenceName="Itemsibfks")]
		public ItemFlingEffect FlingEffect { get; set; }

		/// <summary>
		/// item_flag_map_ibfk_1_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="ItemId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<ItemFlagMap> Itemflagmapibfks { get; set; }

		/// <summary>
		/// item_flavor_summaries_ibfk_2_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="ItemId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<ItemFlavorSummary> Itemflavorsummariesibfks { get; set; }

		/// <summary>
		/// item_flavor_text_ibfk_3_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="ItemId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<ItemFlavorText> Itemflavortextibfks { get; set; }

		/// <summary>
		/// item_game_indices_ibfk_2_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="ItemId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<ItemGameIndex> Itemgameindicesibfks { get; set; }

		/// <summary>
		/// item_names_ibfk_2_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="ItemId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<ItemName> Itemnamesibfks { get; set; }

		/// <summary>
		/// item_prose_ibfk_2_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="ItemId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<ItemProse> Itemproseibfks { get; set; }

		/// <summary>
		/// machines_ibfk_1_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="ItemId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<Machine> Machinesibfks { get; set; }

		/// <summary>
		/// pokemon_evolution_ibfk_9_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="HeldItemId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<PokemonEvolution> PokemonEvolutionIbfk9BackReferences { get; set; }

		/// <summary>
		/// pokemon_evolution_ibfk_6_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="TriggerItemId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<PokemonEvolution> Pokemonevolutionibfks { get; set; }

		/// <summary>
		/// pokemon_items_ibfk_2_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="ItemId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<PokemonItem> Pokemonibfks { get; set; }

		#endregion
	}
}

#pragma warning restore 1591
