//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    With additional support for multiple files.
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Infrastructure.Models
{
	using System;
	using System.Collections.Generic;
	using System.Linq;

	using Infrastructure.Core.Business.Data;

	using LinqToDB;
	using LinqToDB.Mapping;

	[Table("item_flavor_text")]
	public partial class ItemFlavorText : BusinessData
	{
		[Column("item_id"),          PrimaryKey(1), NotNull] public int    ItemId         { get; set; } // int(11)
		[Column("version_group_id"), PrimaryKey(2), NotNull] public int    VersionGroupId { get; set; } // int(11)
		[Column("language_id"),      PrimaryKey(3), NotNull] public int    LanguageId     { get; set; } // int(11)
		[Column("flavor_text"),                     NotNull] public string FlavorText     { get; set; } // text

		#region Associations

		/// <summary>
		/// item_flavor_text_ibfk_3
		/// </summary>
		[Association(ThisKey="ItemId", OtherKey="Id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="item_flavor_text_ibfk_3", BackReferenceName="Itemflavortextibfks")]
		public Item Item { get; set; }

		/// <summary>
		/// item_flavor_text_ibfk_2
		/// </summary>
		[Association(ThisKey="LanguageId", OtherKey="Id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="item_flavor_text_ibfk_2", BackReferenceName="Itemflavortextibfks")]
		public Language Language { get; set; }

		/// <summary>
		/// item_flavor_text_ibfk_1
		/// </summary>
		[Association(ThisKey="VersionGroupId", OtherKey="Id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="item_flavor_text_ibfk_1", BackReferenceName="Itemflavortextibfks")]
		public VersionGroup VersionGroup { get; set; }

		#endregion
	}
}

#pragma warning restore 1591
