//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    With additional support for multiple files.
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Infrastructure.Models
{
	using System;
	using System.Collections.Generic;
	using System.Linq;

	using Infrastructure.Core.Business.Data;

	using LinqToDB;
	using LinqToDB.Mapping;

	[Table("item_flag_map")]
	public partial class ItemFlagMap : BusinessData
	{
		[Column("item_id"),      PrimaryKey(1), NotNull] public int ItemId     { get; set; } // int(11)
		[Column("item_flag_id"), PrimaryKey(2), NotNull] public int ItemFlagId { get; set; } // int(11)

		#region Associations

		/// <summary>
		/// item_flag_map_ibfk_1
		/// </summary>
		[Association(ThisKey="ItemId", OtherKey="Id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="item_flag_map_ibfk_1", BackReferenceName="Itemflagmapibfks")]
		public Item Item { get; set; }

		/// <summary>
		/// item_flag_map_ibfk_2
		/// </summary>
		[Association(ThisKey="ItemFlagId", OtherKey="Id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="item_flag_map_ibfk_2", BackReferenceName="Itemflagmapibfks")]
		public ItemFlag ItemFlag { get; set; }

		#endregion
	}
}

#pragma warning restore 1591
