//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    With additional support for multiple files.
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Infrastructure.Models
{
	using System;
	using System.Collections.Generic;
	using System.Linq;

	using Infrastructure.Core.Business.Data;

	using LinqToDB;
	using LinqToDB.Mapping;

	[Table("item_fling_effects")]
	public partial class ItemFlingEffect : BusinessData
	{
		[Column("id"), PrimaryKey, NotNull] public int Id { get; set; } // int(11)

		#region Associations

		/// <summary>
		/// item_fling_effect_prose_ibfk_1_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="ItemFlingEffectId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<ItemFlingEffectProse> Itemflingeffectproseibfks { get; set; }

		/// <summary>
		/// items_ibfk_2_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="FlingEffectId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<Item> Itemsibfks { get; set; }

		#endregion
	}
}

#pragma warning restore 1591
