//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    With additional support for multiple files.
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Infrastructure.Models
{
	using System;
	using System.Collections.Generic;
	using System.Linq;

	using Infrastructure.Core.Business.Data;

	using LinqToDB;
	using LinqToDB.Mapping;

	[Table("languages")]
	public partial class Language : BusinessData
	{
		[Column("id"),         PrimaryKey,  NotNull] public int    Id         { get; set; } // int(11)
		[Column("iso639"),                  NotNull] public string Iso639     { get; set; } // varchar(79)
		[Column("iso3166"),                 NotNull] public string Iso3166    { get; set; } // varchar(79)
		[Column("identifier"),              NotNull] public string Identifier { get; set; } // varchar(79)
		[Column("official"),                NotNull] public bool   Official   { get; set; } // tinyint(1)
		[Column("order"),         Nullable         ] public int?   Order      { get; set; } // int(11)

		#region Associations

		/// <summary>
		/// ability_changelog_prose_ibfk_2_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="LocalLanguageId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<AbilityChangelogProse> Abilitychangelogproseibfks { get; set; }

		/// <summary>
		/// ability_flavor_text_ibfk_3_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="LanguageId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<AbilityFlavorText> Abilityflavortextibfks { get; set; }

		/// <summary>
		/// ability_names_ibfk_1_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="LocalLanguageId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<AbilityName> Abilitynamesibfks { get; set; }

		/// <summary>
		/// ability_prose_ibfk_1_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="LocalLanguageId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<AbilityProse> Abilityproseibfks { get; set; }

		/// <summary>
		/// berry_firmness_names_ibfk_2_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="LocalLanguageId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<BerryFirmnessName> Berryfirmnessnamesibfks { get; set; }

		/// <summary>
		/// characteristic_text_ibfk_2_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="LocalLanguageId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<CharacteristicText> Characteristictextibfks { get; set; }

		/// <summary>
		/// conquest_episode_names_ibfk_2_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="LocalLanguageId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<ConquestEpisodeName> Conquestepisodenamesibfks { get; set; }

		/// <summary>
		/// conquest_kingdom_names_ibfk_1_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="LocalLanguageId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<ConquestKingdomName> Conquestkingdomnamesibfks { get; set; }

		/// <summary>
		/// conquest_move_displacement_prose_ibfk_1_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="LocalLanguageId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<ConquestMoveDisplacementProse> Conquestmovedisplacementproseibfks { get; set; }

		/// <summary>
		/// conquest_move_effect_prose_ibfk_2_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="LocalLanguageId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<ConquestMoveEffectProse> Conquestmoveeffectproseibfks { get; set; }

		/// <summary>
		/// conquest_move_range_prose_ibfk_1_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="LocalLanguageId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<ConquestMoveRangeProse> Conquestmoverangeproseibfks { get; set; }

		/// <summary>
		/// conquest_stat_names_ibfk_1_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="LocalLanguageId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<ConquestStatName> Conqueststatnamesibfks { get; set; }

		/// <summary>
		/// conquest_warrior_names_ibfk_1_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="LocalLanguageId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<ConquestWarriorName> Conquestwarriornamesibfks { get; set; }

		/// <summary>
		/// conquest_warrior_skill_names_ibfk_1_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="LocalLanguageId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<ConquestWarriorSkillName> Conquestwarriorskillnamesibfks { get; set; }

		/// <summary>
		/// conquest_warrior_stat_names_ibfk_2_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="LocalLanguageId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<ConquestWarriorStatName> Conquestwarriorstatnamesibfks { get; set; }

		/// <summary>
		/// contest_effect_prose_ibfk_2_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="LocalLanguageId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<ContestEffectProse> Contesteffectproseibfks { get; set; }

		/// <summary>
		/// contest_type_names_ibfk_2_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="LocalLanguageId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<ContestTypeName> Contesttypenamesibfks { get; set; }

		/// <summary>
		/// egg_group_prose_ibfk_1_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="LocalLanguageId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<EggGroupProse> Egggroupproseibfks { get; set; }

		/// <summary>
		/// encounter_condition_prose_ibfk_2_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="LocalLanguageId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<EncounterConditionProse> Encounterconditionproseibfks { get; set; }

		/// <summary>
		/// encounter_condition_value_prose_ibfk_2_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="LocalLanguageId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<EncounterConditionValueProse> Encounterconditionvalueproseibfks { get; set; }

		/// <summary>
		/// encounter_method_prose_ibfk_2_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="LocalLanguageId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<EncounterMethodProse> Encountermethodproseibfks { get; set; }

		/// <summary>
		/// evolution_trigger_prose_ibfk_2_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="LocalLanguageId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<EvolutionTriggerProse> Evolutiontriggerproseibfks { get; set; }

		/// <summary>
		/// generation_names_ibfk_2_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="LocalLanguageId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<GenerationName> Generationnamesibfks { get; set; }

		/// <summary>
		/// growth_rate_prose_ibfk_2_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="LocalLanguageId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<GrowthRateProse> Growthrateproseibfks { get; set; }

		/// <summary>
		/// item_category_prose_ibfk_1_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="LocalLanguageId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<ItemCategoryProse> Itemcategoryproseibfks { get; set; }

		/// <summary>
		/// item_flag_prose_ibfk_2_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="LocalLanguageId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<ItemFlagProse> Itemflagproseibfks { get; set; }

		/// <summary>
		/// item_flavor_summaries_ibfk_1_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="LocalLanguageId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<ItemFlavorSummary> Itemflavorsummariesibfks { get; set; }

		/// <summary>
		/// item_flavor_text_ibfk_2_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="LanguageId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<ItemFlavorText> Itemflavortextibfks { get; set; }

		/// <summary>
		/// item_fling_effect_prose_ibfk_2_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="LocalLanguageId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<ItemFlingEffectProse> Itemflingeffectproseibfks { get; set; }

		/// <summary>
		/// item_names_ibfk_1_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="LocalLanguageId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<ItemName> Itemnamesibfks { get; set; }

		/// <summary>
		/// item_pocket_names_ibfk_2_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="LocalLanguageId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<ItemPocketName> Itempocketnamesibfks { get; set; }

		/// <summary>
		/// item_prose_ibfk_1_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="LocalLanguageId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<ItemProse> Itemproseibfks { get; set; }

		/// <summary>
		/// language_names_ibfk_2_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="LocalLanguageId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<LanguageName> LanguageNamesIbfk2BackReferences { get; set; }

		/// <summary>
		/// language_names_ibfk_1_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="LanguageId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<LanguageName> Languagenamesibfks { get; set; }

		/// <summary>
		/// location_area_prose_ibfk_1_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="LocalLanguageId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<LocationAreaProse> Locationareaproseibfks { get; set; }

		/// <summary>
		/// location_names_ibfk_2_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="LocalLanguageId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<LocationName> Locationnamesibfks { get; set; }

		/// <summary>
		/// move_battle_style_prose_ibfk_2_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="LocalLanguageId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<MoveBattleStyleProse> Movebattlestyleproseibfks { get; set; }

		/// <summary>
		/// move_damage_class_prose_ibfk_2_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="LocalLanguageId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<MoveDamageClassProse> Movedamageclassproseibfks { get; set; }

		/// <summary>
		/// move_effect_changelog_prose_ibfk_1_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="LocalLanguageId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<MoveEffectChangelogProse> Moveeffectchangelogproseibfks { get; set; }

		/// <summary>
		/// move_effect_prose_ibfk_2_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="LocalLanguageId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<MoveEffectProse> Moveeffectproseibfks { get; set; }

		/// <summary>
		/// move_flag_prose_ibfk_1_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="LocalLanguageId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<MoveFlagProse> Moveflagproseibfks { get; set; }

		/// <summary>
		/// move_flavor_summaries_ibfk_2_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="LocalLanguageId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<MoveFlavorSummary> Moveflavorsummariesibfks { get; set; }

		/// <summary>
		/// move_flavor_text_ibfk_3_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="LanguageId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<MoveFlavorText> Moveflavortextibfks { get; set; }

		/// <summary>
		/// move_meta_ailment_names_ibfk_1_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="LocalLanguageId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<MoveMetaAilmentName> Movemetaailmentnamesibfks { get; set; }

		/// <summary>
		/// move_meta_category_prose_ibfk_2_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="LocalLanguageId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<MoveMetaCategoryProse> Movemetacategoryproseibfks { get; set; }

		/// <summary>
		/// move_names_ibfk_1_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="LocalLanguageId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<MoveName> Movenamesibfks { get; set; }

		/// <summary>
		/// move_target_prose_ibfk_1_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="LocalLanguageId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<MoveTargetProse> Movetargetproseibfks { get; set; }

		/// <summary>
		/// nature_names_ibfk_2_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="LocalLanguageId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<NatureName> Naturenamesibfks { get; set; }

		/// <summary>
		/// pal_park_area_names_ibfk_1_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="LocalLanguageId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<PalParkAreaName> Palparkareanamesibfks { get; set; }

		/// <summary>
		/// pokeathlon_stat_names_ibfk_2_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="LocalLanguageId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<PokeathlonStatName> Pokeathlonstatnamesibfks { get; set; }

		/// <summary>
		/// pokedex_prose_ibfk_1_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="LocalLanguageId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<PokedexProse> Pokedexproseibfks { get; set; }

		/// <summary>
		/// pokemon_color_names_ibfk_1_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="LocalLanguageId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<PokemonColorName> Pokemoncolornamesibfks { get; set; }

		/// <summary>
		/// pokemon_form_names_ibfk_1_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="LocalLanguageId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<PokemonFormName> Pokemonformnamesibfks { get; set; }

		/// <summary>
		/// pokemon_habitat_names_ibfk_1_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="LocalLanguageId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<PokemonHabitatName> Pokemonhabitatnamesibfks { get; set; }

		/// <summary>
		/// pokemon_move_method_prose_ibfk_2_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="LocalLanguageId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<PokemonMoveMethodProse> Pokemonmovemethodproseibfks { get; set; }

		/// <summary>
		/// pokemon_shape_prose_ibfk_2_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="LocalLanguageId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<PokemonShapeProse> Pokemonshapeproseibfks { get; set; }

		/// <summary>
		/// pokemon_species_flavor_summaries_ibfk_2_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="LocalLanguageId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<PokemonSpeciesFlavorSummary> Pokemonspeciesflavorsummariesibfks { get; set; }

		/// <summary>
		/// pokemon_species_flavor_text_ibfk_2_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="LanguageId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<PokemonSpeciesFlavorText> Pokemonspeciesflavortextibfks { get; set; }

		/// <summary>
		/// pokemon_species_names_ibfk_1_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="LocalLanguageId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<PokemonSpeciesName> Pokemonspeciesnamesibfks { get; set; }

		/// <summary>
		/// pokemon_species_prose_ibfk_2_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="LocalLanguageId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<PokemonSpeciesProse> Pokemonspeciesproseibfks { get; set; }

		/// <summary>
		/// region_names_ibfk_2_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="LocalLanguageId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<RegionName> Regionnamesibfks { get; set; }

		/// <summary>
		/// stat_names_ibfk_1_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="LocalLanguageId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<StatName> Statnamesibfks { get; set; }

		/// <summary>
		/// super_contest_effect_prose_ibfk_2_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="LocalLanguageId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<SuperContestEffectProse> Supercontesteffectproseibfks { get; set; }

		/// <summary>
		/// type_names_ibfk_1_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="LocalLanguageId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<TypeName> Typenamesibfks { get; set; }

		/// <summary>
		/// version_names_ibfk_1_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="LocalLanguageId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<VersionName> Versionnamesibfks { get; set; }

		#endregion
	}
}

#pragma warning restore 1591
