//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    With additional support for multiple files.
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Infrastructure.Models
{
	using System;
	using System.Collections.Generic;
	using System.Linq;

	using Infrastructure.Core.Business.Data;

	using LinqToDB;
	using LinqToDB.Mapping;

	[Table("locations")]
	public partial class Location : BusinessData
	{
		[Column("id"),         PrimaryKey,  NotNull] public int    Id         { get; set; } // int(11)
		[Column("region_id"),     Nullable         ] public int?   RegionId   { get; set; } // int(11)
		[Column("identifier"),              NotNull] public string Identifier { get; set; } // varchar(79)

		#region Associations

		/// <summary>
		/// location_areas_ibfk_1_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="LocationId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<LocationArea> Locationareasibfks { get; set; }

		/// <summary>
		/// location_game_indices_ibfk_1_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="LocationId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<LocationGameIndex> Locationgameindicesibfks { get; set; }

		/// <summary>
		/// location_names_ibfk_1_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="LocationId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<LocationName> Locationnamesibfks { get; set; }

		/// <summary>
		/// pokemon_evolution_ibfk_4_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="LocationId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<PokemonEvolution> Pokemonevolutionibfks { get; set; }

		/// <summary>
		/// locations_ibfk_1
		/// </summary>
		[Association(ThisKey="RegionId", OtherKey="Id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="locations_ibfk_1", BackReferenceName="Locationsibfks")]
		public Region Region { get; set; }

		#endregion
	}
}

#pragma warning restore 1591
