//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    With additional support for multiple files.
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Infrastructure.Models
{
	using System;
	using System.Collections.Generic;
	using System.Linq;

	using Infrastructure.Core.Business.Data;

	using LinqToDB;
	using LinqToDB.Mapping;

	[Table("location_area_encounter_rates")]
	public partial class LocationAreaEncounterRate : BusinessData
	{
		[Column("location_area_id"),    PrimaryKey(1), NotNull] public int  LocationAreaId    { get; set; } // int(11)
		[Column("encounter_method_id"), PrimaryKey(2), NotNull] public int  EncounterMethodId { get; set; } // int(11)
		[Column("version_id"),          PrimaryKey(3), NotNull] public int  VersionId         { get; set; } // int(11)
		[Column("rate"),                   Nullable           ] public int? Rate              { get; set; } // int(11)

		#region Associations

		/// <summary>
		/// location_area_encounter_rates_ibfk_1
		/// </summary>
		[Association(ThisKey="EncounterMethodId", OtherKey="Id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="location_area_encounter_rates_ibfk_1", BackReferenceName="Locationareaencounterratesibfks")]
		public EncounterMethod EncounterMethod { get; set; }

		/// <summary>
		/// location_area_encounter_rates_ibfk_2
		/// </summary>
		[Association(ThisKey="LocationAreaId", OtherKey="Id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="location_area_encounter_rates_ibfk_2", BackReferenceName="Locationareaencounterratesibfks")]
		public LocationArea LocationArea { get; set; }

		/// <summary>
		/// location_area_encounter_rates_ibfk_3
		/// </summary>
		[Association(ThisKey="VersionId", OtherKey="Id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="location_area_encounter_rates_ibfk_3", BackReferenceName="Locationareaencounterratesibfks")]
		public Version Version { get; set; }

		#endregion
	}
}

#pragma warning restore 1591
