//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    With additional support for multiple files.
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Infrastructure.Models
{
	using System;
	using System.Collections.Generic;
	using System.Linq;

	using Infrastructure.Core.Business.Data;

	using LinqToDB;
	using LinqToDB.Mapping;

	[Table("location_areas")]
	public partial class LocationArea : BusinessData
	{
		[Column("id"),          PrimaryKey,  NotNull] public int    Id         { get; set; } // int(11)
		[Column("location_id"),              NotNull] public int    LocationId { get; set; } // int(11)
		[Column("game_index"),               NotNull] public int    GameIndex  { get; set; } // int(11)
		[Column("identifier"),     Nullable         ] public string Identifier { get; set; } // varchar(79)

		#region Associations

		/// <summary>
		/// encounters_ibfk_1_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="LocationAreaId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<Encounter> Encountersibfks { get; set; }

		/// <summary>
		/// location_areas_ibfk_1
		/// </summary>
		[Association(ThisKey="LocationId", OtherKey="Id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="location_areas_ibfk_1", BackReferenceName="Locationareasibfks")]
		public Location Location { get; set; }

		/// <summary>
		/// location_area_encounter_rates_ibfk_2_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="LocationAreaId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<LocationAreaEncounterRate> Locationareaencounterratesibfks { get; set; }

		/// <summary>
		/// location_area_prose_ibfk_2_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="LocationAreaId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<LocationAreaProse> Locationareaproseibfks { get; set; }

		#endregion
	}
}

#pragma warning restore 1591
