//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    With additional support for multiple files.
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Infrastructure.Models
{
	using System;
	using System.Collections.Generic;
	using System.Linq;

	using Infrastructure.Core.Business.Data;

	using LinqToDB;
	using LinqToDB.Mapping;

	[Table("machines")]
	public partial class Machine : BusinessData
	{
		[Column("machine_number"),   PrimaryKey(1), NotNull] public int MachineNumber  { get; set; } // int(11)
		[Column("version_group_id"), PrimaryKey(2), NotNull] public int VersionGroupId { get; set; } // int(11)
		[Column("item_id"),                         NotNull] public int ItemId         { get; set; } // int(11)
		[Column("move_id"),                         NotNull] public int MoveId         { get; set; } // int(11)

		#region Associations

		/// <summary>
		/// machines_ibfk_1
		/// </summary>
		[Association(ThisKey="ItemId", OtherKey="Id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="machines_ibfk_1", BackReferenceName="Machinesibfks")]
		public Item Item { get; set; }

		/// <summary>
		/// machines_ibfk_2
		/// </summary>
		[Association(ThisKey="MoveId", OtherKey="Id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="machines_ibfk_2", BackReferenceName="Machinesibfks")]
		public Move Move { get; set; }

		/// <summary>
		/// machines_ibfk_3
		/// </summary>
		[Association(ThisKey="VersionGroupId", OtherKey="Id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="machines_ibfk_3", BackReferenceName="Machinesibfks")]
		public VersionGroup VersionGroup { get; set; }

		#endregion
	}
}

#pragma warning restore 1591
