//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    With additional support for multiple files.
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Infrastructure.Models
{
	using System;
	using System.Collections.Generic;
	using System.Linq;

	using Infrastructure.Core.Business.Data;

	using LinqToDB;
	using LinqToDB.Mapping;

	[Table("move_meta_categories")]
	public partial class MoveMetaCategory : BusinessData
	{
		[Column("id"),         PrimaryKey, NotNull] public int    Id         { get; set; } // int(11)
		[Column("identifier"),             NotNull] public string Identifier { get; set; } // varchar(79)

		#region Associations

		/// <summary>
		/// move_meta_category_prose_ibfk_1_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="MoveMetaCategoryId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<MoveMetaCategoryProse> Movemetacategoryproseibfks { get; set; }

		/// <summary>
		/// move_meta_ibfk_3_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="MetaCategoryId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<MoveMeta> Movemetaibfks { get; set; }

		#endregion
	}
}

#pragma warning restore 1591
