//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    With additional support for multiple files.
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Infrastructure.Models
{
	using System;
	using System.Collections.Generic;
	using System.Linq;

	using Infrastructure.Core.Business.Data;

	using LinqToDB;
	using LinqToDB.Mapping;

	[Table("move_changelog")]
	public partial class MoveChangelog : BusinessData
	{
		[Column("move_id"),                     PrimaryKey(1), NotNull] public int    MoveId                  { get; set; } // int(11)
		[Column("changed_in_version_group_id"), PrimaryKey(2), NotNull] public int    ChangedInVersionGroupId { get; set; } // int(11)
		[Column("type_id"),                        Nullable           ] public int?   TypeId                  { get; set; } // int(11)
		[Column("power"),                          Nullable           ] public short? Power                   { get; set; } // smallint(6)
		[Column("pp"),                             Nullable           ] public short? Pp                      { get; set; } // smallint(6)
		[Column("accuracy"),                       Nullable           ] public short? Accuracy                { get; set; } // smallint(6)
		[Column("priority"),                       Nullable           ] public short? Priority                { get; set; } // smallint(6)
		[Column("target_id"),                      Nullable           ] public int?   TargetId                { get; set; } // int(11)
		[Column("effect_id"),                      Nullable           ] public int?   EffectId                { get; set; } // int(11)
		[Column("effect_chance"),                  Nullable           ] public int?   EffectChance            { get; set; } // int(11)

		#region Associations

		/// <summary>
		/// move_changelog_ibfk_3
		/// </summary>
		[Association(ThisKey="ChangedInVersionGroupId", OtherKey="Id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="move_changelog_ibfk_3", BackReferenceName="Movechangelogibfks")]
		public VersionGroup ChangedInVersionGroup { get; set; }

		/// <summary>
		/// move_changelog_ibfk_1
		/// </summary>
		[Association(ThisKey="EffectId", OtherKey="Id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="move_changelog_ibfk_1", BackReferenceName="Movechangelogibfks")]
		public MoveEffect Effect { get; set; }

		/// <summary>
		/// move_changelog_ibfk_2
		/// </summary>
		[Association(ThisKey="MoveId", OtherKey="Id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="move_changelog_ibfk_2", BackReferenceName="Movechangelogibfks")]
		public Move Move { get; set; }

		/// <summary>
		/// move_changelog_ibfk_5
		/// </summary>
		[Association(ThisKey="TargetId", OtherKey="Id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="move_changelog_ibfk_5", BackReferenceName="Movechangelogibfks")]
		public MoveTarget Target { get; set; }

		/// <summary>
		/// move_changelog_ibfk_4
		/// </summary>
		[Association(ThisKey="TypeId", OtherKey="Id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="move_changelog_ibfk_4", BackReferenceName="Movechangelogibfks")]
		public Type Type { get; set; }

		#endregion
	}
}

#pragma warning restore 1591
