//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    With additional support for multiple files.
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Infrastructure.Models
{
	using System;
	using System.Collections.Generic;
	using System.Linq;

	using Infrastructure.Core.Business.Data;

	using LinqToDB;
	using LinqToDB.Mapping;

	[Table("move_effect_changelog")]
	public partial class MoveEffectChangelog : BusinessData
	{
		[Column("id"),                          PrimaryKey, NotNull] public int Id                      { get; set; } // int(11)
		[Column("effect_id"),                               NotNull] public int EffectId                { get; set; } // int(11)
		[Column("changed_in_version_group_id"),             NotNull] public int ChangedInVersionGroupId { get; set; } // int(11)

		#region Associations

		/// <summary>
		/// move_effect_changelog_ibfk_1
		/// </summary>
		[Association(ThisKey="ChangedInVersionGroupId", OtherKey="Id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="move_effect_changelog_ibfk_1", BackReferenceName="Moveeffectchangelogibfks")]
		public VersionGroup ChangedInVersionGroup { get; set; }

		/// <summary>
		/// move_effect_changelog_ibfk_2
		/// </summary>
		[Association(ThisKey="EffectId", OtherKey="Id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="move_effect_changelog_ibfk_2", BackReferenceName="Moveeffectchangelogibfks")]
		public MoveEffect Effect { get; set; }

		/// <summary>
		/// move_effect_changelog_prose_ibfk_2_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="MoveEffectChangelogId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<MoveEffectChangelogProse> Moveeffectchangelogproseibfks { get; set; }

		#endregion
	}
}

#pragma warning restore 1591
