//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    With additional support for multiple files.
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Infrastructure.Models
{
	using System;
	using System.Collections.Generic;
	using System.Linq;

	using Infrastructure.Core.Business.Data;

	using LinqToDB;
	using LinqToDB.Mapping;

	[Table("move_meta")]
	public partial class MoveMeta : BusinessData
	{
		[Column("move_id"),          PrimaryKey,  NotNull] public int  MoveId         { get; set; } // int(11)
		[Column("meta_category_id"),              NotNull] public int  MetaCategoryId { get; set; } // int(11)
		[Column("meta_ailment_id"),               NotNull] public int  MetaAilmentId  { get; set; } // int(11)
		[Column("min_hits"),            Nullable         ] public int? MinHits        { get; set; } // int(11)
		[Column("max_hits"),            Nullable         ] public int? MaxHits        { get; set; } // int(11)
		[Column("min_turns"),           Nullable         ] public int? MinTurns       { get; set; } // int(11)
		[Column("max_turns"),           Nullable         ] public int? MaxTurns       { get; set; } // int(11)
		[Column("drain"),                         NotNull] public int  Drain          { get; set; } // int(11)
		[Column("healing"),                       NotNull] public int  Healing        { get; set; } // int(11)
		[Column("crit_rate"),                     NotNull] public int  CritRate       { get; set; } // int(11)
		[Column("ailment_chance"),                NotNull] public int  AilmentChance  { get; set; } // int(11)
		[Column("flinch_chance"),                 NotNull] public int  FlinchChance   { get; set; } // int(11)
		[Column("stat_chance"),                   NotNull] public int  StatChance     { get; set; } // int(11)

		#region Associations

		/// <summary>
		/// move_meta_ibfk_1
		/// </summary>
		[Association(ThisKey="MetaAilmentId", OtherKey="Id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="move_meta_ibfk_1", BackReferenceName="Movemetaibfks")]
		public MoveMetaAilment MetaAilment { get; set; }

		/// <summary>
		/// move_meta_ibfk_3
		/// </summary>
		[Association(ThisKey="MetaCategoryId", OtherKey="Id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="move_meta_ibfk_3", BackReferenceName="Movemetaibfks")]
		public MoveMetaCategory MetaCategory { get; set; }

		/// <summary>
		/// move_meta_ibfk_2
		/// </summary>
		[Association(ThisKey="MoveId", OtherKey="Id", CanBeNull=false, Relationship=Relationship.OneToOne, KeyName="move_meta_ibfk_2", BackReferenceName="Movemetaibfk")]
		public Move Move { get; set; }

		#endregion
	}
}

#pragma warning restore 1591
