//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    With additional support for multiple files.
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Infrastructure.Models
{
	using System;
	using System.Collections.Generic;
	using System.Linq;

	using Infrastructure.Core.Business.Data;

	using LinqToDB;
	using LinqToDB.Mapping;

	[Table("nature_pokeathlon_stats")]
	public partial class NaturePokeathlonStat : BusinessData
	{
		[Column("nature_id"),          PrimaryKey(1), NotNull] public int NatureId         { get; set; } // int(11)
		[Column("pokeathlon_stat_id"), PrimaryKey(2), NotNull] public int PokeathlonStatId { get; set; } // int(11)
		[Column("max_change"),                        NotNull] public int MaxChange        { get; set; } // int(11)

		#region Associations

		/// <summary>
		/// nature_pokeathlon_stats_ibfk_1
		/// </summary>
		[Association(ThisKey="NatureId", OtherKey="Id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="nature_pokeathlon_stats_ibfk_1", BackReferenceName="Naturepokeathlonstatsibfks")]
		public Nature Nature { get; set; }

		/// <summary>
		/// nature_pokeathlon_stats_ibfk_2
		/// </summary>
		[Association(ThisKey="PokeathlonStatId", OtherKey="Id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="nature_pokeathlon_stats_ibfk_2", BackReferenceName="Naturepokeathlonstatsibfks")]
		public PokeathlonStat PokeathlonStat { get; set; }

		#endregion
	}
}

#pragma warning restore 1591
