//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    With additional support for multiple files.
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Infrastructure.Models
{
	using System;
	using System.Collections.Generic;
	using System.Linq;

	using Infrastructure.Core.Business.Data;

	using LinqToDB;
	using LinqToDB.Mapping;

	[Table("natures")]
	public partial class Nature : BusinessData
	{
		[Column("id"),                PrimaryKey, NotNull] public int    Id              { get; set; } // int(11)
		[Column("identifier"),                    NotNull] public string Identifier      { get; set; } // varchar(79)
		[Column("decreased_stat_id"),             NotNull] public int    DecreasedStatId { get; set; } // int(11)
		[Column("increased_stat_id"),             NotNull] public int    IncreasedStatId { get; set; } // int(11)
		[Column("hates_flavor_id"),               NotNull] public int    HatesFlavorId   { get; set; } // int(11)
		[Column("likes_flavor_id"),               NotNull] public int    LikesFlavorId   { get; set; } // int(11)
		[Column("game_index"),                    NotNull] public int    GameIndex       { get; set; } // int(11)

		#region Associations

		/// <summary>
		/// natures_ibfk_3
		/// </summary>
		[Association(ThisKey="DecreasedStatId", OtherKey="Id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="natures_ibfk_3", BackReferenceName="Naturesibfks")]
		public Stat DecreasedStat { get; set; }

		/// <summary>
		/// natures_ibfk_2
		/// </summary>
		[Association(ThisKey="HatesFlavorId", OtherKey="Id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="natures_ibfk_2", BackReferenceName="NaturesIbfk2BackReferences")]
		public ContestType HatesFlavor { get; set; }

		/// <summary>
		/// natures_ibfk_4
		/// </summary>
		[Association(ThisKey="IncreasedStatId", OtherKey="Id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="natures_ibfk_4", BackReferenceName="NaturesIbfk4BackReferences")]
		public Stat IncreasedStat { get; set; }

		/// <summary>
		/// natures_ibfk_1
		/// </summary>
		[Association(ThisKey="LikesFlavorId", OtherKey="Id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="natures_ibfk_1", BackReferenceName="Naturesibfks")]
		public ContestType LikesFlavor { get; set; }

		/// <summary>
		/// nature_battle_style_preferences_ibfk_1_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="NatureId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<NatureBattleStylePreference> Naturebattlestylepreferencesibfks { get; set; }

		/// <summary>
		/// nature_names_ibfk_1_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="NatureId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<NatureName> Naturenamesibfks { get; set; }

		/// <summary>
		/// nature_pokeathlon_stats_ibfk_1_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="NatureId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<NaturePokeathlonStat> Naturepokeathlonstatsibfks { get; set; }

		#endregion
	}
}

#pragma warning restore 1591
