//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    With additional support for multiple files.
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Infrastructure.Models
{
	using System;
	using System.Collections.Generic;
	using System.Linq;

	using Infrastructure.Core.Business.Data;

	using LinqToDB;
	using LinqToDB.Mapping;

	[Table("nature_battle_style_preferences")]
	public partial class NatureBattleStylePreference : BusinessData
	{
		[Column("nature_id"),            PrimaryKey(1), NotNull] public int NatureId          { get; set; } // int(11)
		[Column("move_battle_style_id"), PrimaryKey(2), NotNull] public int MoveBattleStyleId { get; set; } // int(11)
		[Column("low_hp_preference"),                   NotNull] public int LowHpPreference   { get; set; } // int(11)
		[Column("high_hp_preference"),                  NotNull] public int HighHpPreference  { get; set; } // int(11)

		#region Associations

		/// <summary>
		/// nature_battle_style_preferences_ibfk_2
		/// </summary>
		[Association(ThisKey="MoveBattleStyleId", OtherKey="Id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="nature_battle_style_preferences_ibfk_2", BackReferenceName="Naturebattlestylepreferencesibfks")]
		public MoveBattleStyle MoveBattleStyle { get; set; }

		/// <summary>
		/// nature_battle_style_preferences_ibfk_1
		/// </summary>
		[Association(ThisKey="NatureId", OtherKey="Id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="nature_battle_style_preferences_ibfk_1", BackReferenceName="Naturebattlestylepreferencesibfks")]
		public Nature Nature { get; set; }

		#endregion
	}
}

#pragma warning restore 1591
