//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    With additional support for multiple files.
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Infrastructure.Models
{
	using System;
	using System.Collections.Generic;
	using System.Linq;

	using Infrastructure.Core.Business.Data;

	using LinqToDB;
	using LinqToDB.Mapping;

	[Table("pal_park")]
	public partial class PalPark : BusinessData
	{
		[Column("species_id"), PrimaryKey, NotNull] public int SpeciesId { get; set; } // int(11)
		[Column("area_id"),                NotNull] public int AreaId    { get; set; } // int(11)
		[Column("base_score"),             NotNull] public int BaseScore { get; set; } // int(11)
		[Column("rate"),                   NotNull] public int Rate      { get; set; } // int(11)

		#region Associations

		/// <summary>
		/// pal_park_ibfk_1
		/// </summary>
		[Association(ThisKey="AreaId", OtherKey="Id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="pal_park_ibfk_1", BackReferenceName="Palparkibfks")]
		public PalParkArea Area { get; set; }

		/// <summary>
		/// pal_park_ibfk_2
		/// </summary>
		[Association(ThisKey="SpeciesId", OtherKey="Id", CanBeNull=false, Relationship=Relationship.OneToOne, KeyName="pal_park_ibfk_2", BackReferenceName="Palparkibfk")]
		public PokemonSpecies Species { get; set; }

		#endregion
	}
}

#pragma warning restore 1591
