//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    With additional support for multiple files.
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Infrastructure.Models
{
	using System;
	using System.Collections.Generic;
	using System.Linq;

	using Infrastructure.Core.Business.Data;

	using LinqToDB;
	using LinqToDB.Mapping;

	[Table("pokemon_dex_numbers")]
	public partial class PokemonDexNumber : BusinessData
	{
		[Column("species_id"),     PrimaryKey(1), NotNull] public int SpeciesId     { get; set; } // int(11)
		[Column("pokedex_id"),     PrimaryKey(2), NotNull] public int PokedexId     { get; set; } // int(11)
		[Column("pokedex_number"),                NotNull] public int PokedexNumber { get; set; } // int(11)

		#region Associations

		/// <summary>
		/// pokemon_dex_numbers_ibfk_1
		/// </summary>
		[Association(ThisKey="PokedexId", OtherKey="Id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="pokemon_dex_numbers_ibfk_1", BackReferenceName="Pokemondexnumbersibfks")]
		public Pokedex Pokedex { get; set; }

		/// <summary>
		/// pokemon_dex_numbers_ibfk_2
		/// </summary>
		[Association(ThisKey="SpeciesId", OtherKey="Id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="pokemon_dex_numbers_ibfk_2", BackReferenceName="Pokemondexnumbersibfks")]
		public PokemonSpecies Species { get; set; }

		#endregion
	}
}

#pragma warning restore 1591
