//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    With additional support for multiple files.
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Infrastructure.Models
{
	using System;
	using System.Collections.Generic;
	using System.Linq;

	using Infrastructure.Core.Business.Data;

	using LinqToDB;
	using LinqToDB.Mapping;

	[Table("pokeathlon_stats")]
	public partial class PokeathlonStat : BusinessData
	{
		[Column("id"),         PrimaryKey, NotNull] public int    Id         { get; set; } // int(11)
		[Column("identifier"),             NotNull] public string Identifier { get; set; } // varchar(79)

		#region Associations

		/// <summary>
		/// nature_pokeathlon_stats_ibfk_2_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="PokeathlonStatId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<NaturePokeathlonStat> Naturepokeathlonstatsibfks { get; set; }

		/// <summary>
		/// pokeathlon_stat_names_ibfk_1_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="PokeathlonStatId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<PokeathlonStatName> Pokeathlonstatnamesibfks { get; set; }

		/// <summary>
		/// pokemon_form_pokeathlon_stats_ibfk_2_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="PokeathlonStatId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<PokemonFormPokeathlonStat> Pokemonformpokeathlonstatsibfks { get; set; }

		#endregion
	}
}

#pragma warning restore 1591
