//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    With additional support for multiple files.
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Infrastructure.Models
{
	using System;
	using System.Collections.Generic;
	using System.Linq;

	using Infrastructure.Core.Business.Data;

	using LinqToDB;
	using LinqToDB.Mapping;

	[Table("pokemon_game_indices")]
	public partial class PokemonGameIndex : BusinessData
	{
		[Column("pokemon_id"), PrimaryKey(1), NotNull] public int PokemonId { get; set; } // int(11)
		[Column("version_id"), PrimaryKey(2), NotNull] public int VersionId { get; set; } // int(11)
		[Column("game_index"),                NotNull] public int GameIndex { get; set; } // int(11)

		#region Associations

		/// <summary>
		/// pokemon_game_indices_ibfk_2
		/// </summary>
		[Association(ThisKey="PokemonId", OtherKey="Id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="pokemon_game_indices_ibfk_2", BackReferenceName="Gameindicesibfks")]
		public Pokemon Pokemon { get; set; }

		/// <summary>
		/// pokemon_game_indices_ibfk_1
		/// </summary>
		[Association(ThisKey="VersionId", OtherKey="Id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="pokemon_game_indices_ibfk_1", BackReferenceName="Pokemongameindicesibfks")]
		public Version Version { get; set; }

		#endregion
	}
}

#pragma warning restore 1591
