//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    With additional support for multiple files.
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Infrastructure.Models
{
	using System;
	using System.Collections.Generic;
	using System.Linq;

	using Infrastructure.Core.Business.Data;

	using LinqToDB;
	using LinqToDB.Mapping;

	[Table("pokemon_form_pokeathlon_stats")]
	public partial class PokemonFormPokeathlonStat : BusinessData
	{
		[Column("pokemon_form_id"),    PrimaryKey(1), NotNull] public int PokemonFormId    { get; set; } // int(11)
		[Column("pokeathlon_stat_id"), PrimaryKey(2), NotNull] public int PokeathlonStatId { get; set; } // int(11)
		[Column("minimum_stat"),                      NotNull] public int MinimumStat      { get; set; } // int(11)
		[Column("base_stat"),                         NotNull] public int BaseStat         { get; set; } // int(11)
		[Column("maximum_stat"),                      NotNull] public int MaximumStat      { get; set; } // int(11)

		#region Associations

		/// <summary>
		/// pokemon_form_pokeathlon_stats_ibfk_2
		/// </summary>
		[Association(ThisKey="PokeathlonStatId", OtherKey="Id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="pokemon_form_pokeathlon_stats_ibfk_2", BackReferenceName="Pokemonformpokeathlonstatsibfks")]
		public PokeathlonStat PokeathlonStat { get; set; }

		/// <summary>
		/// pokemon_form_pokeathlon_stats_ibfk_1
		/// </summary>
		[Association(ThisKey="PokemonFormId", OtherKey="Id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="pokemon_form_pokeathlon_stats_ibfk_1", BackReferenceName="Pokemonformpokeathlonstatsibfks")]
		public PokemonForm PokemonForm { get; set; }

		#endregion
	}
}

#pragma warning restore 1591
