//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    With additional support for multiple files.
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Infrastructure.Models
{
	using System;
	using System.Collections.Generic;
	using System.Linq;

	using Infrastructure.Core.Business.Data;

	using LinqToDB;
	using LinqToDB.Mapping;

	[Table("pokemon_forms")]
	public partial class PokemonForm : BusinessData
	{
		[Column("id"),                             PrimaryKey,  NotNull] public int    Id                         { get; set; } // int(11)
		[Column("identifier"),                                  NotNull] public string Identifier                 { get; set; } // varchar(79)
		[Column("form_identifier"),                   Nullable         ] public string FormIdentifier             { get; set; } // varchar(79)
		[Column("pokemon_id"),                                  NotNull] public int    PokemonId                  { get; set; } // int(11)
		[Column("introduced_in_version_group_id"),    Nullable         ] public int?   IntroducedInVersionGroupId { get; set; } // int(11)
		[Column("is_default"),                                  NotNull] public bool   IsDefault                  { get; set; } // tinyint(1)
		[Column("is_battle_only"),                              NotNull] public bool   IsBattleOnly               { get; set; } // tinyint(1)
		[Column("is_mega"),                                     NotNull] public bool   IsMega                     { get; set; } // tinyint(1)
		[Column("form_order"),                                  NotNull] public int    FormOrder                  { get; set; } // int(11)
		[Column("order"),                                       NotNull] public int    Order                      { get; set; } // int(11)
		[Column("icon"),                              Nullable         ] public byte[] Icon                       { get; set; } // blob
		[Column("sprite"),                            Nullable         ] public byte[] Sprite                     { get; set; } // blob

		#region Associations

		/// <summary>
		/// pokemon_forms_ibfk_2
		/// </summary>
		[Association(ThisKey="IntroducedInVersionGroupId", OtherKey="Id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="pokemon_forms_ibfk_2", BackReferenceName="Pokemonformsibfks")]
		public VersionGroup IntroducedInVersionGroup { get; set; }

		/// <summary>
		/// pokemon_forms_ibfk_1
		/// </summary>
		[Association(ThisKey="PokemonId", OtherKey="Id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="pokemon_forms_ibfk_1", BackReferenceName="Formsibfks")]
		public Pokemon Pokemon { get; set; }

		/// <summary>
		/// pokemon_form_generations_ibfk_1_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="PokemonFormId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<PokemonFormGeneration> Pokemonformgenerationsibfks { get; set; }

		/// <summary>
		/// pokemon_form_names_ibfk_2_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="PokemonFormId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<PokemonFormName> Pokemonformnamesibfks { get; set; }

		/// <summary>
		/// pokemon_form_pokeathlon_stats_ibfk_1_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="PokemonFormId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<PokemonFormPokeathlonStat> Pokemonformpokeathlonstatsibfks { get; set; }

		#endregion
	}
}

#pragma warning restore 1591
