//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    With additional support for multiple files.
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Infrastructure.Models
{
	using System;
	using System.Collections.Generic;
	using System.Linq;

	using Infrastructure.Core.Business.Data;

	using LinqToDB;
	using LinqToDB.Mapping;

	[Table("pokemon")]
	public partial class Pokemon : BusinessData
	{
		[Column("id"),              PrimaryKey,  NotNull] public int    Id             { get; set; } // int(11)
		[Column("identifier"),                   NotNull] public string Identifier     { get; set; } // varchar(79)
		[Column("species_id"),         Nullable         ] public int?   SpeciesId      { get; set; } // int(11)
		[Column("height"),                       NotNull] public int    Height         { get; set; } // int(11)
		[Column("weight"),                       NotNull] public int    Weight         { get; set; } // int(11)
		[Column("base_experience"),              NotNull] public int    BaseExperience { get; set; } // int(11)
		[Column("order"),                        NotNull] public int    Order          { get; set; } // int(11)
		[Column("is_default"),                   NotNull] public bool   IsDefault      { get; set; } // tinyint(1)

		#region Associations

		/// <summary>
		/// pokemon_abilities_ibfk_1_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="PokemonId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<PokemonAbility> Abilitiesibfks { get; set; }

		/// <summary>
		/// encounters_ibfk_4_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="PokemonId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<Encounter> Encountersibfks { get; set; }

		/// <summary>
		/// pokemon_forms_ibfk_1_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="PokemonId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<PokemonForm> Formsibfks { get; set; }

		/// <summary>
		/// pokemon_game_indices_ibfk_2_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="PokemonId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<PokemonGameIndex> Gameindicesibfks { get; set; }

		/// <summary>
		/// pokemon_items_ibfk_1_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="PokemonId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<PokemonItem> Itemsibfks { get; set; }

		/// <summary>
		/// pokemon_moves_ibfk_3_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="PokemonId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<PokemonMove> Movesibfks { get; set; }

		/// <summary>
		/// pokemon_ibfk_1
		/// </summary>
		[Association(ThisKey="SpeciesId", OtherKey="Id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="pokemon_ibfk_1", BackReferenceName="Pokemonibfks")]
		public PokemonSpecies Species { get; set; }

		/// <summary>
		/// pokemon_stats_ibfk_1_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="PokemonId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<PokemonStat> Statsibfks { get; set; }

		/// <summary>
		/// pokemon_types_ibfk_1_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="PokemonId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<PokemonType> Typesibfks { get; set; }

		#endregion
	}
}

#pragma warning restore 1591
