//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    With additional support for multiple files.
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Infrastructure.Models
{
	using System;
	using System.Collections.Generic;
	using System.Linq;

	using Infrastructure.Core.Business.Data;

	using LinqToDB;
	using LinqToDB.Mapping;

	[Table("pokemon_species_flavor_text")]
	public partial class PokemonSpeciesFlavorText : BusinessData
	{
		[Column("species_id"),  PrimaryKey(1), NotNull] public int    SpeciesId  { get; set; } // int(11)
		[Column("version_id"),  PrimaryKey(2), NotNull] public int    VersionId  { get; set; } // int(11)
		[Column("language_id"), PrimaryKey(3), NotNull] public int    LanguageId { get; set; } // int(11)
		[Column("flavor_text"),                NotNull] public string FlavorText { get; set; } // text

		#region Associations

		/// <summary>
		/// pokemon_species_flavor_text_ibfk_2
		/// </summary>
		[Association(ThisKey="LanguageId", OtherKey="Id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="pokemon_species_flavor_text_ibfk_2", BackReferenceName="Pokemonspeciesflavortextibfks")]
		public Language Language { get; set; }

		/// <summary>
		/// pokemon_species_flavor_text_ibfk_1
		/// </summary>
		[Association(ThisKey="SpeciesId", OtherKey="Id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="pokemon_species_flavor_text_ibfk_1", BackReferenceName="Pokemonspeciesflavortextibfks")]
		public PokemonSpecies Species { get; set; }

		/// <summary>
		/// pokemon_species_flavor_text_ibfk_3
		/// </summary>
		[Association(ThisKey="VersionId", OtherKey="Id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="pokemon_species_flavor_text_ibfk_3", BackReferenceName="Pokemonspeciesflavortextibfks")]
		public Version Version { get; set; }

		#endregion
	}
}

#pragma warning restore 1591
