//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    With additional support for multiple files.
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Infrastructure.Models
{
	using System;
	using System.Collections.Generic;
	using System.Linq;

	using Infrastructure.Core.Business.Data;

	using LinqToDB;
	using LinqToDB.Mapping;

	[Table("pokemon_stats")]
	public partial class PokemonStat : BusinessData
	{
		[Column("pokemon_id"), PrimaryKey(1), NotNull] public int PokemonId { get; set; } // int(11)
		[Column("stat_id"),    PrimaryKey(2), NotNull] public int StatId    { get; set; } // int(11)
		[Column("base_stat"),                 NotNull] public int BaseStat  { get; set; } // int(11)
		[Column("effort"),                    NotNull] public int Effort    { get; set; } // int(11)

		#region Associations

		/// <summary>
		/// pokemon_stats_ibfk_1
		/// </summary>
		[Association(ThisKey="PokemonId", OtherKey="Id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="pokemon_stats_ibfk_1", BackReferenceName="Statsibfks")]
		public Pokemon Pokemon { get; set; }

		/// <summary>
		/// pokemon_stats_ibfk_2
		/// </summary>
		[Association(ThisKey="StatId", OtherKey="Id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="pokemon_stats_ibfk_2", BackReferenceName="Pokemonibfks")]
		public Stat Stat { get; set; }

		#endregion
	}
}

#pragma warning restore 1591
