//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    With additional support for multiple files.
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Infrastructure.Models
{
	using System;
	using System.Collections.Generic;
	using System.Linq;

	using Infrastructure.Core.Business.Data;

	using LinqToDB;
	using LinqToDB.Mapping;

	[Table("stats")]
	public partial class Stat : BusinessData
	{
		[Column("id"),              PrimaryKey,  NotNull] public int    Id            { get; set; } // int(11)
		[Column("damage_class_id"),    Nullable         ] public int?   DamageClassId { get; set; } // int(11)
		[Column("identifier"),                   NotNull] public string Identifier    { get; set; } // varchar(79)
		[Column("is_battle_only"),               NotNull] public bool   IsBattleOnly  { get; set; } // tinyint(1)
		[Column("game_index"),         Nullable         ] public int?   GameIndex     { get; set; } // int(11)

		#region Associations

		/// <summary>
		/// characteristics_ibfk_1_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="StatId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<Characteristic> Characteristicsibfks { get; set; }

		/// <summary>
		/// stats_ibfk_1
		/// </summary>
		[Association(ThisKey="DamageClassId", OtherKey="Id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="stats_ibfk_1", BackReferenceName="Statsibfks")]
		public MoveDamageClass DamageClass { get; set; }

		/// <summary>
		/// move_meta_stat_changes_ibfk_1_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="StatId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<MoveMetaStatChange> Movemetastatchangesibfks { get; set; }

		/// <summary>
		/// natures_ibfk_4_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="IncreasedStatId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<Nature> NaturesIbfk4BackReferences { get; set; }

		/// <summary>
		/// natures_ibfk_3_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="DecreasedStatId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<Nature> Naturesibfks { get; set; }

		/// <summary>
		/// pokemon_stats_ibfk_2_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="StatId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<PokemonStat> Pokemonibfks { get; set; }

		/// <summary>
		/// stat_names_ibfk_2_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="StatId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<StatName> Statnamesibfks { get; set; }

		#endregion
	}
}

#pragma warning restore 1591
