//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    With additional support for multiple files.
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Infrastructure.Models
{
	using System;
	using System.Collections.Generic;
	using System.Linq;

	using Infrastructure.Core.Business.Data;

	using LinqToDB;
	using LinqToDB.Mapping;

	[Table("super_contest_combos")]
	public partial class SuperContestCombo : BusinessData
	{
		[Column("first_move_id"),  PrimaryKey(1), NotNull] public int FirstMoveId  { get; set; } // int(11)
		[Column("second_move_id"), PrimaryKey(2), NotNull] public int SecondMoveId { get; set; } // int(11)

		#region Associations

		/// <summary>
		/// super_contest_combos_ibfk_2
		/// </summary>
		[Association(ThisKey="FirstMoveId", OtherKey="Id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="super_contest_combos_ibfk_2", BackReferenceName="SuperContestCombosIbfk2BackReferences")]
		public Move FirstMove { get; set; }

		/// <summary>
		/// super_contest_combos_ibfk_1
		/// </summary>
		[Association(ThisKey="SecondMoveId", OtherKey="Id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="super_contest_combos_ibfk_1", BackReferenceName="Supercontestcombosibfks")]
		public Move SecondMove { get; set; }

		#endregion
	}
}

#pragma warning restore 1591
