//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    With additional support for multiple files.
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Infrastructure.Models
{
	using System;
	using System.Collections.Generic;
	using System.Linq;

	using Infrastructure.Core.Business.Data;

	using LinqToDB;
	using LinqToDB.Mapping;

	[Table("version_groups")]
	public partial class VersionGroup : BusinessData
	{
		[Column("id"),            PrimaryKey,  NotNull] public int    Id           { get; set; } // int(11)
		[Column("identifier"),                 NotNull] public string Identifier   { get; set; } // varchar(79)
		[Column("generation_id"),              NotNull] public int    GenerationId { get; set; } // int(11)
		[Column("order"),            Nullable         ] public int?   Order        { get; set; } // int(11)

		#region Associations

		/// <summary>
		/// ability_changelog_ibfk_2_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="ChangedInVersionGroupId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<AbilityChangelog> Abilitychangelogibfks { get; set; }

		/// <summary>
		/// ability_flavor_text_ibfk_1_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="VersionGroupId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<AbilityFlavorText> Abilityflavortextibfks { get; set; }

		/// <summary>
		/// encounter_slots_ibfk_1_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="VersionGroupId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<EncounterSlot> Encounterslotsibfks { get; set; }

		/// <summary>
		/// version_groups_ibfk_1
		/// </summary>
		[Association(ThisKey="GenerationId", OtherKey="Id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="version_groups_ibfk_1", BackReferenceName="Versiongroupsibfks")]
		public Generation Generation { get; set; }

		/// <summary>
		/// item_flavor_text_ibfk_1_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="VersionGroupId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<ItemFlavorText> Itemflavortextibfks { get; set; }

		/// <summary>
		/// machines_ibfk_3_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="VersionGroupId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<Machine> Machinesibfks { get; set; }

		/// <summary>
		/// move_changelog_ibfk_3_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="ChangedInVersionGroupId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<MoveChangelog> Movechangelogibfks { get; set; }

		/// <summary>
		/// move_effect_changelog_ibfk_1_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="ChangedInVersionGroupId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<MoveEffectChangelog> Moveeffectchangelogibfks { get; set; }

		/// <summary>
		/// move_flavor_text_ibfk_2_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="VersionGroupId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<MoveFlavorText> Moveflavortextibfks { get; set; }

		/// <summary>
		/// pokedex_version_groups_ibfk_2_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="VersionGroupId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<PokedexVersionGroup> Pokedexversiongroupsibfks { get; set; }

		/// <summary>
		/// pokemon_forms_ibfk_2_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="IntroducedInVersionGroupId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<PokemonForm> Pokemonformsibfks { get; set; }

		/// <summary>
		/// pokemon_moves_ibfk_4_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="VersionGroupId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<PokemonMove> Pokemonmovesibfks { get; set; }

		/// <summary>
		/// version_group_pokemon_move_methods_ibfk_1_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="VersionGroupId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<VersionGroupPokemonMoveMethod> Versiongrouppokemonmovemethodsibfks { get; set; }

		/// <summary>
		/// version_group_regions_ibfk_1_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="VersionGroupId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<VersionGroupRegion> Versiongroupregionsibfks { get; set; }

		/// <summary>
		/// versions_ibfk_1_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="VersionGroupId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<Version> Versionsibfks { get; set; }

		#endregion
	}
}

#pragma warning restore 1591
