//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    With additional support for multiple files.
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Infrastructure.Models
{
	using System;
	using System.Collections.Generic;
	using System.Linq;

	using Infrastructure.Core.Business.Data;

	using LinqToDB;
	using LinqToDB.Mapping;

	[Table("versions")]
	public partial class Version : BusinessData
	{
		[Column("id"),               PrimaryKey, NotNull] public int    Id             { get; set; } // int(11)
		[Column("version_group_id"),             NotNull] public int    VersionGroupId { get; set; } // int(11)
		[Column("identifier"),                   NotNull] public string Identifier     { get; set; } // varchar(79)

		#region Associations

		/// <summary>
		/// encounters_ibfk_3_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="VersionId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<Encounter> Encountersibfks { get; set; }

		/// <summary>
		/// location_area_encounter_rates_ibfk_3_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="VersionId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<LocationAreaEncounterRate> Locationareaencounterratesibfks { get; set; }

		/// <summary>
		/// pokemon_game_indices_ibfk_1_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="VersionId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<PokemonGameIndex> Pokemongameindicesibfks { get; set; }

		/// <summary>
		/// pokemon_items_ibfk_3_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="VersionId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<PokemonItem> Pokemonitemsibfks { get; set; }

		/// <summary>
		/// pokemon_species_flavor_text_ibfk_3_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="VersionId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<PokemonSpeciesFlavorText> Pokemonspeciesflavortextibfks { get; set; }

		/// <summary>
		/// versions_ibfk_1
		/// </summary>
		[Association(ThisKey="VersionGroupId", OtherKey="Id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="versions_ibfk_1", BackReferenceName="Versionsibfks")]
		public VersionGroup VersionGroup { get; set; }

		/// <summary>
		/// version_names_ibfk_2_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="VersionId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<VersionName> Versionnamesibfks { get; set; }

		#endregion
	}
}

#pragma warning restore 1591
